### ISSUE TITLE
Torznab issues

### ISSUE THREAD

**Issue by ewhal** [NyaaPantsu/nyaa#1017]
change xml fields to `"<torznab:attr name="size" value="257142742" />".` and remove nesting
English translated should also map to 5070. `"<category id="5070" name="Anime" description="Anime" />" `
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" encoding="UTF-8">
should be just `<?xml version="1.0" encoding="UTF-8"?>`
`<subcat id="3000012" name="Anime - Anime Music Video"></subcat>` should be 30012
Same with other categories 
`<limits` limits="300" default="50"></limits> `

should be  `<limits max="300" default="50"></limits>`

**Comment by Taloth** [comment]
Recap & checklist:

- [ ] Change `<torznab>` nesting into individual `<torznab:attr name="size" value="257142742" />` elements. Don't forget to add a global `xmlns:torznab="http://torznab.com/schemas/2015/feed"` attribute on the root 'rss' element, it'll tell xml parsers what 'torznab' means. _(you're free to use whatever you want: `torz:attr` is fine too, as long as `xmlns:torz=...` is defined.)_

- [ ] Consider adding `<category id="5070" name="Anime" description="Anime" />` and return 'English - translated' items in that category as well, it's the default anime category in torznab/newznab.

- [ ] `t=caps`  returns a root `<rss><caps>...</caps></rss>` structure, it should be without the encapsulating `rss`.

- [ ] `<subcat id="3000012" name="Anime - Anime Music Video"></subcat>` probably should be 30012. You're free to do what you want, but it's more in line with what newznab does.

- [ ] `<limits limits="300" default="50">` should be `<limits max="300" default="50">`

- [ ] `/torznab?t=search&extended=1&offset=0` returns 'page number is invalid'. offset=0 is the first page and should be considered the same as no `offset` at all.

- [ ] In the feed result I saw: `<files>0</files>`. This obviously isn't correct coz there's always a file. If the value is unknown, omit it. Same for seeders&leechers.

- [ ] `/torznab?t=search&cat=10000` doesn't seem to honor the `cat`, same for cat=1234 (should return nothing), or cat=20000,40000, which should only return audio and literature.

I couldn't test further without hacking Sonarr to handle the <torznab> nesting, so more later.

**Comment by Taloth** [comment]
`<torznab:attr name="files"></torznab:attr><torznab:attr name="seeders"></torznab:attr>` I meant omit the entire 'attr' element, instead of just the value. sry for not being clearer before.

Also I noticed some items on the feed where the infohash had a space in front, not torznab specific but I think it's missing some input validation somewhere.

Otherwise it's looking good.
