### ISSUE TITLE
Suggestion, replace Markdowns with the older codes

### ISSUE THREAD

**Issue by egozi44** [NyaaPantsu/nyaa#1037]
Markdowns are confusing as hell for people like myself who aren't familiar with them.
When I press the insert image button all I got is " ![](http://)"
pressing on existing image link and than pressing the button will only result in "[(img9.anidb.net/pics/anime/64586456345645http://)"

While is should be 

![](http://img9.anidb.net/pics/anime64586456345645.jpg).
the [] thing make you think you need to add the image link there and if you add it in the ( ) manually it just add another unneeded http://

Needless to say that only adding the image link alone won't make it show up, it  confusing and give users who aren't familiar with it hard time upload Images

**Comment by akuma06** [comment]
If you know html, you can use `<img src="xxx.png" />`

**Comment by kipukun** [comment]
This is already an open issue #687. This can be closed.

**Comment by egozi44** [comment]
I see, hope it will be considered :/
