### ISSUE TITLE
 <guid>https://sukebei.pantsu.catview2317921</guid>   

### ISSUE THREAD

**Issue by ewhal** [NyaaPantsu/nyaa#1051]
<guid>https://sukebei.pantsu.catview2317921</guid>

**Comment by akuma06** [comment]
Git blame PantsuDev :p https://github.com/NyaaPantsu/nyaa/commit/0cfacdd48db6bdfb6d34867dbaf1edafdb589f8e#diff-8f70d5945e28da19821086c987a09336

**Comment by ewhal** [comment]
woops
