### ISSUE TITLE
[NotIssue] UserScript for Duplicate comments fix

### ISSUE THREAD

**Issue by AkatsukiNin** [NyaaPantsu/nyaa#1052]
As title says, removes duplicate comments from torrent page.
[https://gist.github.com/AkatsukiNin/46dad656be7a57dd20c8aaea67ac768a](https://gist.github.com/AkatsukiNin/46dad656be7a57dd20c8aaea67ac768a)
[Nyaa Pantsu Fix.js](https://gist.github.com/AkatsukiNin/46dad656be7a57dd20c8aaea67ac768a/raw/335a1e721f0a53f04ef4decc1ec0a45ffb198f46/Nyaa_Pantsu_Fixes.user.js)

**Comment by Kiloutre** [comment]
I've added a workaround in the website to hide duplicate comments from same users until @ewhal cleans them, this is better since it means everyone (including non-js users) get to have duplicate-free comment zone, and the visual artifact caused by HTML suddenly disappearing is also removed
