### ISSUE TITLE
Respect Accept-Language header

### ISSUE THREAD

**Issue by nyuszika7h** [NyaaPantsu/nyaa#1057]
Please respect the `Accept-Language` HTTP header instead of trying to guess the language based on geolocation. It's annoying when sites do this, Google being the primary example.

Are any users of this site still using buggy browsers which always send English in that header? Even then, if possible, it would be better not to ignore the header for everyone. I know it's just two clicks for people who don't want to use their geolocation-based language too, and it's probably a language the user will know (unless they are using a proxy or something), but still.

**Comment by mitki** [comment]
Pantsu doesn't guess the language based on geolocation though, it indeed uses the accept language header.

**Comment by nyuszika7h** [comment]
Huh. I got Hungarian with `Accept-Language: en-US,en;q=0.7,hu;q=0.3` earlier, but I can't seem to reproduce this now.
