### ISSUE TITLE
Reverse proxy misconfiguration

### ISSUE THREAD

**Issue by mitki** [NyaaPantsu/nyaa#1065]
1.  `transparency.pantsu.cat` 302 redirect to `a.doko.moe`.
2. `dev.pantsu.cat` doesn't redirect to `https://dev.pantsu.cat`.
3. `https://dev.pantsu.cat` doesn't work.
4. `pantsu.cat` `www.pantsu.cat` are redundant, they should redirect to `nyaa.pantsu.cat`
5. `http` to `https` redirects should be 301 instead 302, since they are permanent and it's bad for SEO.

**Comment by Miao14** [comment]
Should be fixed now.
