### ISSUE TITLE
vgmdb.net links/IDs for music releases

### ISSUE THREAD

**Issue by sfan5** [NyaaPantsu/nyaa#1071]
similar to the anidb thing we have already

**Comment by ewhal** [comment]
We could also expand this to vndb ids

**Comment by akuma06** [comment]
More like, we should rename anidb_id to something more general to use

**Comment by ewhal** [comment]
Anidb + vgmdb + vndb would be godly
>Search via id
>Display basic info like cover art and summary

**Comment by 8zIWLjcB** [comment]
https://github.com/ScudLee/anime-lists
Mappings between AniDb.net, theTVDB.com, and themoviedb.org.

**Comment by akuma06** [comment]
Done
