### ISSUE TITLE
Should disallow setting language for a few categories

### ISSUE THREAD

**Issue by sfan5** [NyaaPantsu/nyaa#1077]
such as:
* ~~Anime - English-translated _(always english)_~~
* Audio _(there are lyrics but nobody cares about those)_  **kilo does**
* Literature - English-translated _(duh)_
* ~~Live Action - English-translated~~
* ~~Pictures _(usually no text content)_~~

**Comment by Kiloutre** [comment]
> Audio (there are lyrics but nobody cares about those)
Do you have any other stupid remark you want to share with us

**Comment by 8zIWLjcB** [comment]
No, English-translated can have other languages as well. For example, an anime torrent with English hardsubs and English dubs muxed in is English-translated but has a Japanese audio track as well. So it should be under English-translated and be classified as 2+ languages.

**Comment by sfan5** [comment]
That's true, but I don't think it makes too much sense since "English-translated" would mean Japanese + English in 99% of cases.
Maybe @ElegantMonkey can clarify whether the language field is for the original, translated or both languages

**Comment by akuma06** [comment]
@8zIWLjcB @sfan5 Refactor is taking care of the job now. We now support multiple languages.

* If no english language is selected but you upload to english category, it adds english as a language to the torrent.
* If you upload to a non-english category but you put english as a category, it moves the torrent to the equivalent english category.

We no more shows errors for languages since languages is not a mandatory field and shouldn't stop someone to upload.

**Comment by 8zIWLjcB** [comment]
@sfan5 
What about the following scenario?
Anime is uploaded with english dubs muxed in, japanese audio present, english hardsubs, english subs muxed in. Russian dubs are present in a separate folder. If it qualifies as English-translated (which it should), then you have a case where you have English-translated without English language flag.

**Comment by toynbeeidea** [comment]
Assuming subtitled and/or dubbed anime is in English is a fucking stupid idea.

Assuming raw anime is in Japanese, on the other hand... that makes a bit more sense, no?

**Comment by akuma06** [comment]
Raw =/= japanese. You can have raw that are chinese for example, since the source is a chinese anime.

**Comment by sfan5** [comment]
@toynbeeidea 
This is not about subtitled anime in general, it's about subtitled anime uploaded to the <i>English-translated</i> category.

**Comment by Kiloutre** [comment]
Quite a few torrents get uploaded as _English-translated_ yet have multiple languages, the reason for this is that the _English-translated_ is simply more popular so if the torrent main language is english but that it has other languages (multiple audio channels or subtitles) then as an uploader you want your torrent to be in this category or it will not be seen as much

**Comment by sfan5** [comment]
I too have realized that forcing <i>English-translated</i> to be english-only would be stupid.

**Comment by Kiloutre** [comment]
Should have said it sooner!
![1507591835854](https://user-images.githubusercontent.com/11745692/31373272-b3621c5c-ad99-11e7-955c-4a0ed1b0763c.jpg)

**Comment by Kiloutre** [comment]
ok maybe for literature - english & pictures
audio is a no-no because your opinion about lyrics does not matter

**Comment by Kiloutre** [comment]
i disabled categories on upload for Pictures torrent
i dont wanna do it on litterature because it's all text, there is always the possibility of an user uploading something containing multiple languages
audio can comes in many language too
close your issue or i will kill your family
