### ISSUE TITLE
Only mods can see user torrents

### ISSUE THREAD

**Issue by tomleb** [NyaaPantsu/nyaa#1092]
Login as mods and go to these torrents. Everything is fine.
Logout and you can't see them.
@akuma06 
user/8728/Vodka-dev
user/8807/seiya
user/9647/Izzy
user/8763/Over-Time
user/8718/DefinitelyNotMe
user/8738/TSDM

EDIT: Some user page don't have this problem and can be viewed by non-mod user.

**Comment by akuma06** [comment]
This is an ES issue you need to look if hidden is false by default in es and that status is different than 0.
This behavior doesn't happen with postgres
