### ISSUE TITLE
 kilo | when the page auto-refreshes it keeps giving me old torrents      

### ISSUE THREAD

**Issue by ewhal** [NyaaPantsu/nyaa#1108]

**Comment by Kiloutre** [comment]
![pic](https://user-images.githubusercontent.com/11745692/27849996-bbfb68c6-6151-11e7-89be-8db59c6861c2.png)
Jul 5 torrents are the most recent ones, refreshing the page onyl shows the Jul 5 torrents and not the Jun 16/17 ones

**Comment by kipukun** [comment]
What do you mean by this? Why would June 16/17 torrents show up on the front page?

**Comment by ewhal** [comment]
Seems like it has to do with the auto-refresh js

**Comment by Kiloutre** [comment]
Seems to be fixed?
