### ISSUE TITLE
Suggestion: Annoymous Upload and Captcha

### ISSUE THREAD

**Issue by ShardM** [NyaaPantsu/nyaa#1153]
I just uploaded a torrent annoymously by mistake and there is no way to correct that. Why allow annoymous upload in the first place? Without annoymous, maybe you can remove the annoying captcha. Nyaa hardly had any spam.

Maybe remove the annoymous upload (and with it the Captcha) as it is uncessary.

Thank you

**Comment by akuma06** [comment]
If you uploaded without being logged in. You have to reclaim the torrent by contacting someone in the staff in IRC for example. 
Anon uploads have always been a thing on nyaa and many people don't like to have an account for uploading.

If you have an account, you can also upload as anon by checking the checkbox in the upload form "Upload Anonymously" when uploading. This can be reverted by editing your torrent and unchecking the checkbox.

Finally, we are unfortunately sorry to say this, but we had some issues with people which supposedly didn't like our alternatives and spammed our torrents with "Mein Kampf" fake torrents. So we had to add this security to prevent people from spamming our database with shit. It might be removed someday when things calm down, but for now it's a feature. If you have an account, you can ask to be made a trusted user. Those users don't have the captcha and have their torrents marked as trusted torrents. For that you need to ask someone in the staff by using IRC.

Closing this issue for now, hoping I've answered your questions ;)

**Comment by ShardM** [comment]
Thank you for much for the details explanation.  I will try the IRC channel. See if I can reclaim them.
