### ISSUE TITLE
[Suggestion] - Show how much a user Uploaded/Downloaded

### ISSUE THREAD

**Issue by Venrir** [NyaaPantsu/nyaa#1157]
Will courage some people to seed and fight for a better placement.

**Comment by Kiloutre** [comment]
I implemented upload count which will come on live soon, but download count would involve tracking downloads in the first place which i'm fairly sure not a lot of people will like

**Comment by akuma06** [comment]
We are against all tracking and try to make our users as anonymous as possible. However if @ewhal agrees, we might add an opt-in option to enable a download activity for users. But, in any case, even if we add that this will never be something more than an opt-in option.

**Comment by Kiloutre** [comment]
Upload count implemented and we really never are going to implement download tracking, it'd be more of a bloat than anything

**Comment by Venipa** [comment]
uh i mean counting how much of a size a user uploaded.

**Comment by Kiloutre** [comment]
Alright, total uploaded size added with #1554
