### ISSUE TITLE
When editing torrents that had flags before the multi-flags system, the language checkboxes will ALL be unchecked

### ISSUE THREAD

**Issue by Kiloutre** [NyaaPantsu/nyaa#1183]
![pic](https://user-images.githubusercontent.com/11745692/28212573-5fe6d1c6-68a2-11e7-8dba-0234eee23962.png)
And obviously, submitting the edit remove the flags

**Comment by akuma06** [comment]
The fix is a db one. @ewhal should do an update on languages with their parent counter part. For example `Update torrents SET languages="fr" WHERE languages="fr-fr"`
