### ISSUE TITLE
Dunno where to start

### ISSUE THREAD

**Issue by Miao14** [NyaaPantsu/nyaa#1201]
- [x] Nothing happens whe you click delete in front page mod tools
- [x] User page is cucked https://a.doko.moe/whznoq.png
- [x] FAQ still with official nyaapocalypse, its not needed anymore just change it to FAQ and remove anything related to nyaa (maybe put it on pastebin or something)
- [x] Commenting gives out a 500 error
- [x] Deleting and locking ttorrent with front page mod tools does delete torrent but its not removed from front page.

**Comment by Kiloutre** [comment]
>  Commenting gives out a 500 error
https://dev.pantsu.cat/view/955395
your comments are in there though

**Comment by Miao14** [comment]
m8 they still give out 500 error anyway

**Comment by akuma06** [comment]
All this is fixed it seems
