### ISSUE TITLE
Page parameter in api doesn't work

### ISSUE THREAD

**Issue by Shadey** [NyaaPantsu/nyaa#1251]
https://nyaa.pantsu.cat/api/search?page=1&limit=1 and https://nyaa.pantsu.cat/api/search?page=2&limit=1 are the same and they shouldn't be.

**Comment by akuma06** [comment]
https://nyaa.pantsu.cat/api/search/p/1?xxxx instead of ?page=1

**Comment by akuma06** [comment]
Added the ?page=xx parameter in api v1.1.0 ;)
