### ISSUE TITLE
Search box is unusable

### ISSUE THREAD

**Issue by nick-s-b** [NyaaPantsu/nyaa#1289]
Nyaa's current search box is a usability mess. Here's what it looks like:

![https://i.imgur.com/WVHiGUx.png](https://i.imgur.com/WVHiGUx.png)

Primary function of the search box should be to SEARCH for something, not to refine your search so why is the "Refine" button beside a search box? Refine comes AFTER the search has been done. That "Refine" is called "Advanced Search" on pretty much ever site I've ever used. 
Why is the magnifying glass, the thing you actually have to click to search, less than a 1/3 in size of the Refine button? Smaller target = harder to click. And why doesn't it look like a button?

![https://i.imgur.com/TTG8BMi.png](https://i.imgur.com/TTG8BMi.png)

After you've focused on the Search box and started to type (or pasted something in), why does the box expand? Why does it hide the Sign In link? And after you've clicked on something and the box shrinks again, if you're not careful, you can EASILY click the sign in link by accident. It has happened to me several times.

And here's the competition:

![https://i.imgur.com/LFwSdiS.png](https://i.imgur.com/LFwSdiS.png)

With their search box, you can actually search for something without thinking and precisely having to click on tiny icons. Notice how it looks and behaves like pretty much every search box on the web and the primary function, the search, is obvious and highlighted by a single large icon and there's nothing to confuse you.

**Comment by Kiloutre** [comment]
the search box is expandong on focus, naturally clicking the search icon loses the focus so it un-enxpandong
> Why is the magnifying glass, the thing you actually have to click to search, less than a 1/3

yeah i already expanded that the most i could, making it bigger would create visual artifact so it's probably gonna be redone to occupy more space

**Comment by Kiloutre** [comment]
> Primary function of the search box should be to SEARCH for something, not to refine your search so why is the "Refine" button beside a search box? Refine comes AFTER the search has been done. That "Refine" is called "Advanced Search" on pretty much ever site I've ever used.

Yeah this is something that i was thinking about though, the Refine button looks more like a search button by the position so people might click on it and notice that the form isn't submitted, just that the refine \<div\> is now being shown when they do. I'd like to get it separate from the search box and give it some proper styling as to avoid people clicking on it by mistake, however that would require more space and the header in japanese (the country we get the most traffic and user-uploads from) and some other country seriously lack space, so doing these changes right now would be pretty shit from them. It could be done if the shitty Boards link would be deleted, but that link was added by ewhal4 (owner) and Miao (hosting guy) by straight-up editing the file in the server, it's not even in the code. I've told them to remove it countless times but these guys are complete retards so they never listen nor even answer. Both me and akuma (two main contributors) agree on removing it from there, but we can't make PRs for it as it's not even in the code. If users would be complaining about it then we'd probably see it gone in matter of seconds as no one really cares about it being in the header (it can be moved elsewhere).

**Comment by nick-s-b** [comment]
@Kiloutre You can use a standard-looking search bar. Here's how ebay looks, for example:

![https://i.imgur.com/u8C7IbY.png](https://i.imgur.com/u8C7IbY.png)

Search button is clearly labeled (magnifying glass like .si does it is also OK but Search is so much clearer) and nothing jumps around and nothing confuses the user about what they should click. Advanced link is like Refine (Refine should probably be an option after a user does the initial search and shouldn't even be in the navbar).

Current search "button" doesn't even look like a button and looks like a background graphic.

**Comment by Kiloutre** [comment]
The search button looking like a background graphic has not been fixed
