### ISSUE TITLE
RSS pubDate malformed

### ISSUE THREAD

**Issue by grawity** [NyaaPantsu/nyaa#1308]
The channel and individual items have:

    <pubDate>2017-08-01 13:55:44.364419679 +0200 CEST</pubDate>
    <pubDate>01 Aug 17 13:26 UTC</pubDate>

[Neither of them](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fnyaa.pantsu.cat%2Ffeed) is a valid RFC 2822 date (and the latter is one hour in the future), as a result some feed readers (namely Thunderbird) show _weird_ post dates in year 2031 instead.

_(Well, yes, RSS seems to reference the much more lax RFC 822, but apparently that's not what parsers expect.)_

The expected format for RSS 2.0 would be:

    <pubDate>Tue, 01 Aug 2017 12:15:20 +0000</pubDate>

**Comment by yiiTT** [comment]
Was this fixed? @ewhal

**Comment by yiiTT** [comment]
(fixed)

**Comment by grawity** [comment]
Looks like partly fixed for items in 71b033ccb4f742bd43ef116924fa265868186902 (the year still seems to be in the wrong place, I dunno if Thunderbird will mind that).

**Comment by yiiTT** [comment]
Invalid RFC 2822 @ewhal

**Comment by Kiloutre** [comment]
I fixed it in #1654, however i only fixed it for the RSS. tornzab & eztv use the old format, and i have no idea if it's right or not so i will not touch it until told otherwise
