### ISSUE TITLE
[Sugestion] Catalog Torrents

### ISSUE THREAD

**Issue by SandroHc** [NyaaPantsu/nyaa#1309]
Ability to catalog torrents by anime. That would allow users to navigate by anime name, season, and episode.

**Comment by Kiloutre** [comment]
If i'm not wrong this is precisely what anidb integration will bring so it's currently in the work, but it isn't finished yet and won't be for quite some time

**Comment by SandroHc** [comment]
Should I close this issue and improve upon #1011?

**Comment by Kiloutre** [comment]
Well if you have a somewhat detailed idea on how it should be done then sure

**Comment by akuma06** [comment]
1.1 introduced the tag system, the catalog torrents will be moved to next update :)

**Comment by SandroHc** [comment]
The project is dead.
