### ISSUE TITLE
[Suggestion] Decreasing 'refine' height

### ISSUE THREAD

**Issue by Lamppostmanufacturer** [NyaaPantsu/nyaa#1312]
@Kiloutre 
The refine div is unnecessarily big. This change can reduce its height by about 40%.

![metre](https://user-images.githubusercontent.com/30628803/28867175-792e3912-7775-11e7-9a51-3be54a5cdacf.png)

**Comment by Kiloutre** [comment]
Those are pretty broken flag alignements in your screenshot. What browser are you using and what version?

**Comment by Lamppostmanufacturer** [comment]
FF 54.0.1 (64bit). Also mentionable that im on MacOS
