### ISSUE TITLE
Add translation changelog

### ISSUE THREAD

**Issue by Lamppostmanufacturer** [NyaaPantsu/nyaa#1346]
For the coming content i recommend creating a textfile in the translations folder where the devs write changes to the en-us file and on which line the strings were added. You cant always look through the last 30 pull requests to see what exactly changed.

**Comment by akuma06** [comment]
For add stuff you can currently use the go-i18n command line. It should generate a .untranslated.json with all the untranslated lines (look into this [readme](https://github.com/NyaaPantsu/nyaa/blob/dev/translations/README.md) for more information).

I will try to do it just after translate directory refactoring =)
