### ISSUE TITLE
Getting logged out at least once a day

### ISSUE THREAD

**Issue by Golumpa** [NyaaPantsu/nyaa#1359]
I seem to be getting logged out at least once a day, sometimes within 30 mins to an hour. It's a little annoying.

Not sure what the issue is or how to replicate it as all I know is that sometimes I just need to refresh the page and I'm logged out while other times, it's when the site goes down aka "no torrents found" (which is quite often lately).

Also, may be related in some way but if you change sites (sukubai <--> nyaa) you also get logged out from the other site.

**Comment by akuma06** [comment]
I will try to look into it after tags are done. I might ask @sfan5, if he has time to help on that because it seems to be a weird bug :/

**Comment by sfan5** [comment]
I don't think this is a bug, rather the absence of cookie secret keys in the config combined with periodic restarts of `nyaa`.

**Comment by akuma06** [comment]
Seems to be fixed to me
