### ISSUE TITLE
Can't see my own torrents? and issues that Still present

### ISSUE THREAD

**Issue by egozi44** [NyaaPantsu/nyaa#1373]
So I just notice it but it seem like I can't find my own torrents in the search bar, and no one seed them, I done everything corretly so why? don't tell me it because I upload them as れんちょん Cause that SHOULDN'T happend in any sane site.

Also I saw that while the site finally in working order and went through hell of a upgrade there are few things that were reported again and again and still didn't were added.

*No remember me button

*No bigger cooldown for logging out (can't you just seriously make it infinitely or per month? I personally can count the sites I visit which auto log me out with my fingers...)

*In some browsers I still see the date of uplaoding in my home language rather than the selected language (English)

Aside from that I for once can't find more things to report atm :)

**Comment by egozi44** [comment]
Still can't see any of my torrents, thankfully they getting seeders from nyaa si but that ridicules....

**Comment by akuma06** [comment]
Login is an issue, but we had other things to fix and I don't think there will be "remember me". Just a cookie with a higher expire time.
"Some browser" is not specific enough. If you're talking about IE, might be that it doesn't take the Localize Date argument in JavaScript. Can't do a thing about that unfortunately.
And I don't understand what you say by "Can't see my own torrents". I see mine?

**Comment by egozi44** [comment]
Don't see why it nearly impossible to add remember me button at this day and age, from what I heard it already exist and avaliable only for people who join the development of the site.

and by not seeing my own torrents I meant that I can't find them on the front page after upload or via the search bar at all, not when I log in and not as offline user with different IP and browser, I can see them only on my profile.

also I report it before but all the replies that were recovered from old nyaa are doubled/tripled, can this be fixed?

**Comment by akuma06** [comment]
What I mean is I don't think there will be a forever "remember me" but an expire "remember me" (maybe 1 year). You will still have the checkbox though and if you don't check it, your session will end when you close the browser.
Does it happen only just after upload or even for older torrents?

**Comment by egozi44** [comment]
I belive most sites don't actually have infinite login time, they just make it too long that it make you think it infinite, so yeah 1 year is more than enough, if you could do it (or even 3 months) it will be great.

 It happenes for both new and old torrents, I just never notice my old torrents can't be found with the search bar till now, and the newest torrent I uploaded was more or less few days before I open this thread

**Comment by akuma06** [comment]
@egozi44 I just checked on last commit about the bug "can't see my own torrents" and it seems to work fine. Next update should fix this then :).

**Comment by egozi44** [comment]
alright 

thanks
