### ISSUE TITLE
[dev.pantsu only] 500 Internal Server Error when searching for trusted/a+ or remake

### ISSUE THREAD

**Issue by Kiloutre** [NyaaPantsu/nyaa#1428]
https://dev.pantsu.cat/search?s=2
https://dev.pantsu.cat/search?s=3
https://dev.pantsu.cat/search?s=4

When searching by trusted, a+ or filtering remake, an error 500 happen on dev. It does not happen locally though, even when both local & dev are using the exact same code

**Comment by sfan5** [comment]
very slow but works for me

**Comment by Kiloutre** [comment]
> very slow but works for me

All four of the links work for you? The first and third one should not work, the second and fourth should.

**Comment by sfan5** [comment]
seems i only tested the two which are supposed to work, nvm then
