### ISSUE TITLE
Announcement word-wrapping

### ISSUE THREAD

**Issue by Lamppostmanufacturer** [NyaaPantsu/nyaa#1459]
Is there a `<br>` where it doesnt belong?
![wrapper3](https://user-images.githubusercontent.com/30628803/29959785-4e7f8c52-8ef9-11e7-9ce5-3c3f892907b6.png)

2nd pic may be negligible since that behavior is only on very small widths

**Comment by Kiloutre** [comment]
I manually put that br when making the announcement
About second pic it's intended, i came up with a "fix" three days ago but after looking at it on various texts having empty space under the exclamation mark wasn't looking very aesthetical so i kept it the current way it is now

**Comment by Lamppostmanufacturer** [comment]
So that how it is, thought it behaved incorrectly :^)
