### ISSUE TITLE
Mascot doesn't play sound when clicked

### ISSUE THREAD

**Issue by Kiloutre** [NyaaPantsu/nyaa#1466]
Even though the url in the `<audio>` is the same the website tries to load  `b.doko.moe/znadfr.mp3` instead for some reason

**Comment by akuma06** [comment]
@Kiloutre If you look into `templates/layouts/partials/base.jet.html`, you see that the audio src is `b.doko.moe/znadfr.mp3` for logged user. However when going to `b.doko.moe/znadfr.mp3`, you have error 404 :/. So the file must have been deleted?

**Comment by Kiloutre** [comment]
idk, it works now, loads a.doko.moe instead of b.doko.moe, the file exist on a and not on b
