### ISSUE TITLE
The Anidb ID, VNdb ID, DLsite, VGMdb ID and Video Quality tag fields appear twice both on the upload form and when tagging an existing entry.

### ISSUE THREAD

**Issue by Kiloutre** [NyaaPantsu/nyaa#1472]
please fix

**Comment by akuma06** [comment]
Configuration problem, the tags are set twice in two different config files.

**Comment by Kiloutre** [comment]
ewhal doesn't know how to fix it

**Comment by akuma06** [comment]
But do you still have the problem? I don't see it on dev?
