### ISSUE TITLE
Logging-in on nyaa, dev or sukebei will log you off from the two remaining ones

### ISSUE THREAD

**Issue by Kiloutre** [NyaaPantsu/nyaa#1475]

**Comment by akuma06** [comment]
This is cookie configuration problem. Should have been fixed though. @ewhal

**Comment by Kiloutre** [comment]
@ewhal this problem is getting very annoying especially for me on dev

**Comment by Kiloutre** [comment]
Fixed it by removing getDomainName() on cookie setLogin function and clear
