### ISSUE TITLE
Editing a torrent adds a <br> after every single line break in description

### ISSUE THREAD

**Issue by Kiloutre** [NyaaPantsu/nyaa#1480]
even if JS is disabled
it does it once the form is sent so every line break is effectively constantly doubled with no way around it

**Comment by akuma06** [comment]
Maybe we should remove br html tag?

**Comment by ewhal** [comment]
>Everything is still having `<br/>` added before every line when editing. and adding tags in edit removes all added tags, including what was just added.

**Comment by Kiloutre** [comment]
BBCode support was responsible for that bug so i temporarily disabled it
