### ISSUE TITLE
the torrent i upload to sukebei and https://anidex.info/torrent/70212

### ISSUE THREAD

**Issue by ted423** [NyaaPantsu/nyaa#1484]
but there is a post on nyaa.pantsu.cat

https://sukebei.pantsu.cat/view/2339618
https://nyaa.pantsu.cat/view/975940

**Comment by akuma06** [comment]
Seems like a torrent which was wrongly scrapped by previous scrapper. Do you want to delete it from nyaa and keep only the one in sukebei?

**Comment by ted423** [comment]
@akuma06 I found a lot of sukebei thing on nyaa.pantsu.cat
like https://nyaa.pantsu.cat/view/979143(it's been deleted)
that torrent I upload to nidex.info forget choose ‘hentai’

**Comment by akuma06** [comment]
Yeah we had some problems with our scrapper previously which couldn't make a difference between hentai and non-hentai torrents. This have been fixed though but we still have some hentai torrents on nyaa which need to be removed.

I removed it from nyaa, the issue can be close I think.
