### ISSUE TITLE
Don't show torrent link if file doesn't exist

### ISSUE THREAD

**Issue by Kiloutre** [NyaaPantsu/nyaa#1488]
Having 404 links all over the website is really shit and without a doubt infuriating for a lot of users
Hell, i even got scolded by some friends once because of it...
Checking if the file exist when in listing.html would be pretty bad because it would mean 1 http query per torrent, which would without a doubt considerably slow down the execution of the code
Torrent.FileExists boolean when? You could store the boolean in the DB with torrents and a such hide 404 links very easily?

**Comment by akuma06** [comment]
You don't need to check for file exist by doing http query. If you look into https://github.com/NyaaPantsu/nyaa/blob/dev/controllers/torrent/download.go#L29 you should see that it is actually easy to check if a file exist by looking into the hard drive.
That's how we can display a 404 not found error when you download.
