### ISSUE TITLE
Modpanel has styling issues w/ translations enabled

### ISSUE THREAD

**Issue by sfan5** [NyaaPantsu/nyaa#1510]
![bildschirmfoto_2017-09-05_15-14-43](https://user-images.githubusercontent.com/1042418/30062884-0a370af0-924d-11e7-8496-a82869e3fa03.png)

**Comment by Kiloutre** [comment]
putting so many links in the header was a mistake in the first place, you should move them in the main div and keep all of them constantly shown on any moderation page
