### ISSUE TITLE
On demand torrent file generation for missing torrent files

### ISSUE THREAD

**Issue by ewhal** [NyaaPantsu/nyaa#1517]
https://github.com/anacrolix/torrent/blob/master/cmd/magnet-metainfo/main.go

**Comment by Kiloutre** [comment]
@ewhal plenty of the new users complaining about the torrent links not working
you're the only one that has enough knowledge to do this
pls

**Comment by Kiloutre** [comment]
Also you could directly run the script in download.go should the file be missing, that way we could straight up avoid having it run automatically on every torrent but rather generate files for torrents that actually need it
