### ISSUE TITLE
*.pantsu.cat/feed/ = 404

### ISSUE THREAD

**Issue by Kiloutre** [NyaaPantsu/nyaa#1533]
https://sukebei.pantsu.cat/feed/p/1 works though
but not
https://sukebei.pantsu.cat/feed/

**Comment by MMP0** [comment]
[https://sukebei.pantsu.cat/feed](https://sukebei.pantsu.cat/feed) works

**Comment by Kiloutre** [comment]
I personally get a 404 on it

**Comment by Lamppostmanufacturer** [comment]
Problem exists on non sukebei too. The direct link on Pantsu leads to https://nyaa.pantsu.cat/feed/? which is a 404, however https://nyaa.pantsu.cat/feed werks fine.

**Comment by Kiloutre** [comment]
Was just a wrong URL in the header
