### ISSUE TITLE
Changing password doesn't seem to work

### ISSUE THREAD

**Issue by motbob** [NyaaPantsu/nyaa#1539]
Just what it says, when I go to the account page and try to change the password, the settings page refreshes, there's no notification of anything being done, and the password remains unchanged.

**Comment by Kiloutre** [comment]
I just tried right now and everything seems to work perfectly: putting a too short password (under 6 characters) gives a warning, putting the wrong password gives an alert, and changing the password does say "profile updated successfully"
![test](https://user-images.githubusercontent.com/11745692/30224315-92250bdc-94ce-11e7-9525-e61275d1f46b.png)

**Comment by motbob** [comment]
I've got nothing to say except that it doesn't for me. No notification of success or error.

I just switched browsers (from Firefox to Chrome) and successfully changed it. It may be a cookie issue or some kind of browser issue.

**Comment by Kiloutre** [comment]
I really can't seem to reproduce, do you still get the bug?

**Comment by motbob** [comment]
I don't know, since I can't log in on Firefox and haven't been able to for a long time. No wrong password notification or anything. I'm sure if I cleared my browser cache, it would start working, but...

**Comment by Kiloutre** [comment]
The old issue related to not being able to log in was because of cookies (duplicate session cookie), however there's been a JS fix put in place to clean duplicate cookies a few updates ago, and another update supposedly coming up in an hour or so  makes sure to remove any existing session cookie before creating one (preventing duplicate session cookies again), so should try to log in again

If it stills happens even with these fixes put in place then it would be a brand new issue

**Comment by motbob** [comment]
I can log in now, but I still can't change my password.

**Comment by Kiloutre** [comment]
What browser (& browser version) are you on exactly? It works on latest firefox & chrome for me

**Comment by motbob** [comment]
Firefox, 56.0.1, but I'm sure it's not a browser issue per se but rather a cookie issue, like the login thing. TBH, since I can probably fix the problem by clearing cache but choose not to, you might as well just close the issue.

**Comment by Kiloutre** [comment]
Changing password doesn't have anything to do with cookie or cache so it really should not happen

**Comment by motbob** [comment]
Anyway, just forget it, I changed it in another browser a long time ago, if someone else complains then you can troubleshoot them. Apologies for keeping this open.
