### ISSUE TITLE
commit hash empty

### ISSUE THREAD

**Issue by Kiloutre** [NyaaPantsu/nyaa#1562]

**Comment by akuma06** [comment]
If you speak about commit hash in footer, it's not a bug. You have to use the building command specified on readme or use package.sh

**Comment by Kiloutre** [comment]
<ewhal4> I do 
<ewhal4> every
<ewhal4> time
<ewhal4> go build -v -ldflags="-X main.buildversion=`git rev-parse HEAD`"

**Comment by akuma06** [comment]
If you've read the Readme, you would see that the actual command is: `godep go build -ldflags "-X main.buildversion=$(git rev-parse HEAD)"`

**Comment by Kiloutre** [comment]
i was quoting ewhal by the way
