### ISSUE TITLE
DLsite field doesn't work when fed a string

### ISSUE THREAD

**Issue by Terraeris** [NyaaPantsu/nyaa#1573]
DLsite ID is an integer when entered on the site.(Ex. RJ001001 disappears after being entered whereas 001001 get's turned into 1001 and links to an error page..) It should be a string as to allow the RJ, RE or VJ at the front, along with the six digit number following it or else you get the error page.

**Comment by Kiloutre** [comment]
Looking at _models\torrent.go_, _models\tag.go, models\tag_\ and multiple other files, it seems the 4 main tags are constantly treated as integer so modifying every piece of the code that is related to them is gonna get a bit annoying
would be nice if @akuma06 was there because he created all of this...

**Comment by Kiloutre** [comment]
Temporary workaround has been made: DLSite link has an _RJ_ prefix and IDs under 6 characters long will get filled with zeros, e.g.: **6666** into **006666**

**Comment by yiiTT** [comment]
I thought I informed someone about this before.
edit: oh it was ewhal
"one thing about dlsite is a valid id would start with RJ, VJ, BJ, RE, BE - doujin, pc/soft, ebook/manga, english, gay english and then 6 numbers"

We should split them into Dlsite Prefix and Dlsite ID

**Comment by Kiloutre** [comment]
> We should split them into Dlsite Prefix and Dlsite ID

That seems like a bad idea when we could just have the DLsite as 8 characters long string instead

**Comment by Kiloutre** [comment]
@akuma06 it didn't fix it fully, putting a prefix (e.g **RJ445566**) removes the prefix although the number is still sent, so the tag end up being **445566**

**Comment by akuma06** [comment]
@Kiloutre It does work. I just tried on last commit. Be careful that your column "dlsite" in db is now a varchar and not int.

Plus your last PR has introduced a viewing bug which add "RJ" before the dlsite tag on `templates/torrent/view.jet.html`
