### ISSUE TITLE
Uploading broken on dev

### ISSUE THREAD

**Issue by Kiloutre** [NyaaPantsu/nyaa#1578]
Gives "torrent uploaded successfully!" message but doesn't upload and redirects to **/view/0**

_inb4 "it's your new upload form!"_
No, it happens even with the old one, and regardless if a fucked up HTML allowed the Go to run the code to the point where it redirects you (upload success) then only the Go would be responsible, which is the case here

**edit:** works fine on new DB, and `ALTER TABLE torrents ALTER COLUMN dlsite TYPE varchar(8)` should fix it on current ones if it doesn't do it on it's own

**Comment by akuma06** [comment]
On last commit, it works though

**Comment by Kiloutre** [comment]
I've updated dev to last commit and go builded and it does not work
I even updated & go builded 3 - 4 times just to make sure

**Comment by akuma06** [comment]
Look into your database. It might be because your table column "dlsite" is not a varchar

**Comment by Kiloutre** [comment]
> Look into your database. It might be because your table column "dlsite" is not a varchar

Doesn't that mean that we'll need to run a command on live when updating to ensure it works?

**Comment by akuma06** [comment]
This should be migrated when you run nyaa though. It did on my end. But if you need, you can do an `ALTER TABLE torrents ALTER COLUMN dlsite TYPE varchar(8)` for Postgres

**Comment by Kiloutre** [comment]
>This should be migrated when you run nyaa though.

It did not on dev
