### ISSUE TITLE
"Torrent file not found" page should have magnet link button

### ISSUE THREAD

**Issue by Kiloutre** [NyaaPantsu/nyaa#1579]
@akuma06 how would i go about getting a torrent magnet link just from it's hash in controllers\torrent\download.go, but also making it accessible to the no_results template

**Comment by akuma06** [comment]
Two possibilities:
1. You add an information message "magnet" (`messages.AddInfos("magnet", "xxxx")`) for example and check on the template in the Infos array if there is information "magnet". If there is you display the magnet link by getting it from the Infos array.
2. You use the same thing as you did in search Not Found. You create a new variable and render the template no_results by giving the new variable. Then in the template you check if the variable is set and display the magnet download link.

**Comment by Kiloutre** [comment]
> You use the same thing as you did in search Not Found. You create a new variable and render the template no_results by giving the new variable. Then in the template you check if the variable is set and display the magnet download link.

I did look into that before sending my message, however the code that i added on search.go relied on existing code:
`variables := templates.Commonvariables(c)
variables.Set("Search", searchForm)`
There, searchForm already existed, so did templates.NewSearchForm(c), in fact everything that was needed was already there in order for the following, very important line, to work:
`templates.ModelList(c, "site/torrents/listing.jet.html", models.TorrentsToJSON(torrents), nav, searchForm)`

Here, none of these exist already, it's not like there is a templates.NewTorrentInfos that i could use so i really have no idea where to start from

More important in download.go, the only information that i possess related to the torrent is it's hash. How do i even carry or get the magnet link? I could add a magnet link get parameter on the "torrent file" button's URL, but that'd make torrent links massively long which we do not want considering users paste torrent links in pastebins, 4chan threads and anywhere, really.
Once i do a `messages.AddInfos("magnet", "xxxx")`, how do i access it's value? There doesn't seem to be any example of it in the whole code

**Comment by akuma06** [comment]
You don't need variables.Set("Search", searchForm) since there is no "SearchForm" when you download.
You already have variables := templates.Commonvariables(c) in download.go. So you just have to add the magnet link into the variables variable `variables.Set("magnet", "xxx")`.
To get the magnet link you already have the torrent from the db on line 41. Just move the code upward to use it before and copy/paste how the magnet link is generated in models/torrent.go ToJSON function.
```
package torrentController

import (
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"

	"github.com/NyaaPantsu/nyaa/config"
	"github.com/NyaaPantsu/nyaa/models/torrents"
	"github.com/NyaaPantsu/nyaa/templates"
	"github.com/NyaaPantsu/nyaa/utils/format"
	"github.com/gin-gonic/gin"
)

// DownloadTorrent : Controller for downloading a torrent
func DownloadTorrent(c *gin.Context) {
	hash := c.Param("hash")

	if hash == "" && len(config.Get().Torrents.FileStorage) == 0 {
		//File not found, send 404
		variables := templates.Commonvariables(c)
		templates.Render(c, "errors/torrent_file_missing.jet.html", variables)
		return
	}

	torrent, err := torrents.FindRawByHash(hash)

	if err != nil {
		//File not found, send 404
		variables := templates.Commonvariables(c)
		templates.Render(c, "errors/torrent_file_missing.jet.html", variables)
		return
	}

	//Check if file exists and open
	Openfile, err := os.Open(fmt.Sprintf("%s%c%s.torrent", config.Get().Torrents.FileStorage, os.PathSeparator, hash))
	if err != nil {
		//File not found, send 404
		variables := templates.Commonvariables(c)
		var trackers []string
		if torrent.Trackers == "" {
			trackers = config.Get().Torrents.Trackers.Default
		} else {
			trackers = torrent.GetTrackersArray()
		}
		magnet := format.InfoHashToMagnet(strings.TrimSpace(torrent.Hash), torrent.Name, trackers...)
		variables.Set("magnet", magnet)
		templates.Render(c, "errors/torrent_file_missing.jet.html", variables)
		return
	}
	defer Openfile.Close() //Close after function return

	//Get the file size
	FileStat, _ := Openfile.Stat()                     //Get info from file
	FileSize := strconv.FormatInt(FileStat.Size(), 10) //Get file size as a string

	c.Header("Content-Disposition", fmt.Sprintf("attachment; filename=\"%s.torrent\"", torrent.Name))
	c.Header("Content-Type", "application/x-bittorrent")
	c.Header("Content-Length", FileSize)
	//Send the file
	// We reset the offset to 0
	Openfile.Seek(0, 0)
	io.Copy(c.Writer, Openfile) //'Copy' the file to the client
}
```

**Comment by Kiloutre** [comment]
Ok thank you, i would've learned more if you hadn't spoonfed me though but thank you still, i didn't know i could just do a variables.Set() like that to carry a value in the template
i will handle the rest

**Comment by Kiloutre** [comment]
@akuma06
