### ISSUE TITLE
Add category icons to uploading category dropdown menu

### ISSUE THREAD

**Issue by ewhal** [NyaaPantsu/nyaa#1586]

**Comment by Kiloutre** [comment]
Styling this would be a mess, you have to take into account that category images are 28px tall each, seems more like a gimmick than anything
I disagree

**Comment by akuma06** [comment]
I don't disagree but would be really a hassle to do. Since you can't use the default Select tag and would have to use a combination of Javascript and CSS to simulate it. And like kilo said, the category icons as is, doesn't have the right size for that.

**Comment by Kiloutre** [comment]
Unless someone comes by and develop the idea there's no possible way we're doing this
