### ISSUE TITLE
How to message admin privately?

### ISSUE THREAD

**Issue by RetroGameTalk** [NyaaPantsu/nyaa#1614]
Hi on the old nyaa IRC i asked for a comment i sent to be removed and it was granted, but this backup brought it back (3 times actually). Is it possible to have this comment deleted for good?
To avoid yet another footprint i'd prefer to specify the details privately, how can i do that?
Thanks!

**Comment by akuma06** [comment]
You would have to go on the nyaa pantsu IRC 😄

**Comment by RetroGameTalk** [comment]
Gotcha thanks let's do that.
