### ISSUE TITLE
Mirrors link to pantsu.cat on Fap/Fun link

### ISSUE THREAD

**Issue by Kiloutre** [NyaaPantsu/nyaa#1647]
config.WebAddress() just returns the URL from the default_config.yml
it should try to guess if the website is a mirror and if it is, return the current hostname

**Comment by akuma06** [comment]
They just have to configure their own domain name on their own config.yml . It is always better to configure it through a file that no one can modify except a dev, than to use some http headers which can be falsified.

**Comment by Kiloutre** [comment]
The problem is that they aren't running their own instance of pantsu so they can't have their own config files (i think?), they're all mirroring to the same instance of pantsu
Also even if it's falsified, the web address is just used to get the right link (right fap/fun link in header and faq, right link for the feeds, right link for the email verification mail) so i don't think it can actually do any bad

**Comment by Kiloutre** [comment]
So are we doing this or not?
I spent hours looking at the golang doc to try to get the hostname, tried to look at the headers too, nothing seems to work
If you don't want to do it then we can close the issue
