### ISSUE TITLE
[Api] limit parameter not working past 300

### ISSUE THREAD

**Issue by Kylart** [NyaaPantsu/nyaa#1664]
Hello,

I am currently writing an Api based on yours. I am currently facing a problem though.

It seems the `limit` parameter for results isn't working properly. I'd actually love to get all the results at once by setting the limit parameter to `Infinity` or simply something like `99999`.

To check it simply you can check that url: https://nyaa.pantsu.cat/api/search?q=sakura%20Trick&limit=99999

You'll get only 300 results. Obviously the research term isn't involved.

**Comment by akuma06** [comment]
Yeah the limit parameter actually limits the search results in an interval of 1 to 300. If you want the next results (at least for now) you can move between "pages".
We do this (until now) to prevent high usage of ressources. However, if @ewhal wants to change the limit, it can easily be done by changing the default "MaxTorrentsPerPage" in config.yml
https://github.com/NyaaPantsu/nyaa/blob/d3e50b8ffd959dd555fb8e4557950ba5e7cdbdcc/utils/search/maxtype.go#L17
https://github.com/NyaaPantsu/nyaa/blob/d3e50b8ffd959dd555fb8e4557950ba5e7cdbdcc/config/default_config.yml#L161

**Comment by Kiloutre** [comment]
> it can easily be done by changing the default "MaxTorrentsPerPage" in config.yml

It think if we're gonna increase / remove the limit on the max torrents per page, it should be specific to the API
We don't want to give the user the possibility to load an html page with all 800k torrents

**Comment by Kylart** [comment]
Yea I actually ended up doing that but it's obviously slower. Just wanted to report it as I didn't see anything mentioning it.

_Btw I'm looking for some more information concerning the name of the token parameter when uploading_ 😄

**Comment by Kylart** [comment]
> It think if we're gonna increase / remove the limit on the max torrents per page, it should be specific to the API

Well, I'm currently writing an API fully based on yours with its full extension. I don't know if you'd really like to make an exception for every person writing an pantsu API though.

**Comment by akuma06** [comment]
For the number of torrents per page, it's this parameter:
https://github.com/NyaaPantsu/nyaa/blob/d3e50b8ffd959dd555fb8e4557950ba5e7cdbdcc/config/default_config.yml#L160

Of course if someone actually wants limit=9999 and the max_torrent_per_page=9999 then it will show a big amount of torrent in HTML.

**Comment by akuma06** [comment]
> Well, I'm currently writing an API fully based on yours with its full extension. I don't know if you'd really like to make an exception for every person writing an pantsu API though

Actually we might be able to do that for some app if you apply for it with OAuth2 API. But that would be for the future :'). We don't have much application for the OAuth API for now.

> Btw I'm looking for some more information concerning the name of the token parameter when uploading

You need to send the token as a http header "Authorization". You can have more information here:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization

**Comment by Kylart** [comment]
> You need to send the token as a http header "Authorization"

Oh well done! Thanks for that 😄 

Wouldn't having an official API for major languages be easier to implement? Like one in node.js, one php etc? Just thinking

**Comment by akuma06** [comment]
> Wouldn't having an official API for major languages be easier to implement? Like one in node.js, one php etc? Just thinking

I might not have understood what you meant. If it's about OAuth2 API, this is something useful for some websites that need special access to our DB or if you have a mobile app that wants to use for example "Log In with NyaaPantsu" (like what Google Plus or Facebook do). So it's not for user end but for developpers. The api usage is however the same, just with more possibilities.

> Like one in node.js, one php etc? Just thinking

We are providing the API, not the SDK. We do have a basic example on how to upload in Python (in our scripts repository) but that's it. If someone, however, wants to do a SDK for it, he would be welcome.

**Comment by Kylart** [comment]
> I might not have understood what you meant.

I was actually thinking about the idea of doing SDKs for the most populars langages.

> If someone, however, wants to do a SDK for it, he would be welcome.

That's what I'm working on currently. Would you like me to present it to you when done?

**Comment by akuma06** [comment]
Of course we would happily link to it. If you have some time, go to IRC if you want to have a chat with @ewhal, he is in charge concerning the whole project.

**Comment by Kylart** [comment]
Alright, I'll try hanging out there then! 😄

**Comment by ewhal** [comment]
We can definitely increase the amount.
It was set as a hard limit before when the api was being abused but now no real reason to keep it so low

**Comment by Kylart** [comment]
@akuma06 @ewhal 

So i'm done with my apk. If you mind, you can check it [here](https://github.com/Kylart/Nyaapi) (Check the wiki for detailed documentation).

I posted this here as I couldn't find any of you on IRC

**Comment by Kiloutre** [comment]
Is this still an issue? Should we increase the limit or can we close the issue?

**Comment by Kylart** [comment]
As for me it is not an issue from the beginning, I made my API with that. If no one actually needs to have this changed, we can close it for sure

**Comment by Kiloutre** [comment]
Alright, i'll increase it at 500 still since ewhal said we can increase it
