### ISSUE TITLE
[Api] Category not detected on /update route

### ISSUE THREAD

**Issue by Kylart** [NyaaPantsu/nyaa#1682]
Hello again,

Apparently @akuma06 you're the one with the most knowledge over the API.

So here's a description of my problem.

I send a `PUT` request on `/api/update` via nodejs' request package. Everything's good except for the category which is not parsed/recognised.

My request is like this:
```json
{
  "Content-Type": "multipart/form-data",
  "headers": {
    "Authorization": "my_token"
  },
  "formData": {
    "id": "8",
    "username": "Kylart",
    "name": "Hello world",
    "website_link": "test.test.com",
    "category": "3_6"
  }
}
```

Everything is well recognised except for the `category` field. I built my own version of `nyaa` to debug and it seems the error comes from [here](https://github.com/NyaaPantsu/nyaa/blob/dev/utils/upload/upload.go#L77) as, in the said "ExtractCategory" function, if you try to print `r.Category`, it is empty string.

Also, if I don't give a category, I get a `torrent_cat_invalid` anyway which I think is not normal behaviour?

Am I doing anything wrong with this?

EDIT: Typo in JSON

**Comment by akuma06** [comment]
Hi, if you are sending this request like that it won't work. Look at name website_link and category. It seems the key are not in ".

**Comment by Kylart** [comment]
I just mistyped sorry, everything is sent as expected

EDIT: I realised my phrasing was confusing. I mistyped the code in the issue text only, not in my code. @akuma06
