### ISSUE TITLE
"Exclude" search option

### ISSUE THREAD

**Issue by Kiloutre** [NyaaPantsu/nyaa#1689]
To exclude torrents containing specific keywords
Would be nice to have it useable form the header as well, e.g.
_attack on titan -horriblesubs_

**Comment by yiiTT** [comment]
Some time back someone asked to add an account wide search exclude

**Comment by akuma06** [comment]
@yiiTT This already exists `?nuserID=###`
However, @Kiloutre is asking for keywords exclusion. Since we do have ES, it seems to be weird to not have keyword exclusion in search as it is one of its usefulness compared to sql full text search.

**Comment by yiiTT** [comment]
@akuma06 They wanted a setting in the account where they could exclude things from the search be it users or text. So whenever they would use the search feature when logged in it would append their account wide search exclusions. 

Here is part of a conversation with a user back in mid May 2017 "NT had that one feature to filter by tags. It really made my browsing easier, just excluding [HorribleSubs] or [Deadfish]... like a global filter tag"

**Comment by darkmorpher** [comment]
ewhal

So what's the plan on Filtered query ( searchKeyword *-*excludeThisKeyword) for search?

**Comment by darkmorpher** [comment]
@ewhal

So what's the plan on Filtered query ( searchKeyword **-**excludeThisKeyword) for search?

**Comment by darkmorpher** [comment]
@ewhal

So what's the plan on Filtered query (searchKeyword -excludeThisKeyword) for search?

**Comment by darkmorpher** [comment]
@yiiTT @ewhal

So what's the plan on Filtered query (searchKeyword -excludeThisKeyword) for search?

**Comment by Kiloutre** [comment]
It's already working already, didnt even know it existed but it seems to be in elastic search, and i added it to non-ES searchs too with the update a few minutes ago so that it works even if ES is not enabled/ is down
See for yourself:
https://nyaa.pantsu.cat/search?c=3_6&q=-leopard+dragon+ball+super
https://nyaa.pantsu.cat/search?c=3_6&q=dragon+ball+super
