### ISSUE TITLE
Spanish translation (WIP)

### ISSUE THREAD

**Issue by JuanjoSalvador** [NyaaPantsu/nyaa#1704]
Spanish translation is uncompleted (about 30% of sentences are translated) and has a lot of errors. I'm working on it.

If someone want to join me on the translation, please use my fork.

https://github.com/JuanjoSalvador/nyaa

**Comment by JuanjoSalvador** [comment]
Status: WIP (99% translated)

**Unverified lines or needs a revision:**

ID: `large`
Reasson: Context needed

ID: `old`
Reasson: Context needed

ID: `delay`
Reasson: Context needed/Don't know how to translate

ID: `expire`
Reasson: Context needed/Don't know how to translate

**Comment by Kiloutre** [comment]
> ID: large

Used in refine form: "Between 105MB and 2GB **large**"

> ID: old

It's not used anymore so don't worry about this one

> ID: delay

Not used anymore too

> ID: expire

Used in admin-panel, more precisely the announcements list
It shows at which precise time will the announcement expire
Pictured:
![pic](https://user-images.githubusercontent.com/11745692/32379447-d949fc38-c0ad-11e7-8192-0011bbf34675.png)

**Comment by JuanjoSalvador** [comment]
Thanks @Kiloutre! I'm going to fix that then, 5 minutes.

**Comment by JuanjoSalvador** [comment]
Fixed. Available to merge on #1707
