### ISSUE TITLE
Torrent generation not working on live because port is already in use

### ISSUE THREAD

**Issue by Kiloutre** [NyaaPantsu/nyaa#1716]
Port 50007 (default for anacrolix torrent client) is already in use so the torrent generation is not working on live

> \<ewhal4\> so you probably need to randomize it or make a queue for torrent file generation or something

**Comment by akuma06** [comment]
@Kiloutre just provide this struct to NewClient() instead of nil: https://github.com/anacrolix/torrent/blob/9757f04cf8b0713b41890ca77b9acb3bf22f46e7/cmd/torrent/main.go#L148
And set ListenAddr to ":PORT" with the port the one you want.
