### ISSUE TITLE
Dates messed up again :(

### ISSUE THREAD

**Issue by Taien** [NyaaPantsu/nyaa#1759]
![image](https://user-images.githubusercontent.com/1469026/35472969-9c1a19f0-033e-11e8-9355-293e7b796ac1.png)

All dates, no matter how they're sorted, are currently appearing as such.  When you try to filter on date, you get 500 Internal Server Error.

**Comment by yiiTT** [comment]
Dates are fixed, there was an issue with the date format in ES during the last update.
