### ISSUE TITLE
User Profile RSS feed and display all torrents

### ISSUE THREAD

**Issue by yiiTT** [NyaaPantsu/nyaa#197]
Nyaa had the ability of changing the page type to separate (EX: nyaa.se/?page=separate&user=43553&sort=5) for a user which would be just like the index page but it would list all their torrents. The user profile should also accept the same arguments like the search and appending "feed" to the end of the search should display an RSS feed.

Now instead of adding the "separate" page we would just use "all" after the username.

Here are some URL examples

https://nyaa.pantsu.cat/user/[user_id]/[username]/feed (rss feed of page 1)
https://nyaa.pantsu.cat/user/[user_id]/[username]/feed?c=3_&s=&sort=torrent_id&order=desc&max=50&q= (rss feed of anime max 50)
https://nyaa.pantsu.cat/user/[user_id]/[username]/page/2/feed (rss feed of page 2)

https://nyaa.pantsu.cat/user/[user_id]/[username]/all?c=6_&s=&sort=torrent_id&order=desc&q=CG 
(rss feed that contains string "CG" from pictures and will ignore the max argument)
https://nyaa.pantsu.cat/user/[user_id]/[username]/all/feed (rss feed of all a user's torrents)

**Comment by ElegantMonkey** [comment]
> and will ignore the max argument

Is this a good idea? I mean, I think there should be a limit, for the same reasons why there's a limit on the search page.
