### ISSUE TITLE
multiple dynamic template nesting support

### ISSUE THREAD

**Issue by ripdog** [NyaaPantsu/nyaa#272]
Literally the only difference is which item on the sidebar is highlighted.

**Comment by akuma06** [comment]
That would be possible if the way we use template is less buggy. We router/template.go, you're limited to one dynamic template nesting and the others are static. So the block "content" of profile.html cannot be loaded dynamically but get automatically the block from a _*.html. So the big difference is not the highlighted item, but the block content that get loaded.

**Comment by yiiTT** [comment]
Renamed to properly represent the issue.
