### ISSUE TITLE
Captcha not updated when receiving error

### ISSUE THREAD

**Issue by tomleb** [NyaaPantsu/nyaa#377]
Reproduce:
- Go to any page that has captcha (ie : comments)
- Insert correct captcha but with invalid comments (entering nothing, entering javascript)
- Go back to previous page
- Enter valid comments
- Enter captcha (which is the same as before)
This will result in a bad captcha error page.

**Comment by tomleb** [comment]
Ok here's the problem. The captcha library we are using keeps an internal store and [expire captchas when they are validated](https://github.com/dchest/captcha/blob/master/captcha.go#L138). The library doesn't detect between invalid captchas and expired captchas. In fact someone made an [issue](https://github.com/dchest/captcha/issues/6) a few years ago.

The library hasn't been updated since Jul 28, 2015.

What should we do ? Drop the library for another one ? Fork it and roll our own ? Maybe we can load a new captcha when going back to a previous page ?

**Comment by majestrate** [comment]
**never** roll your own captcha you will get spammed to death after someone figures out how to break it. 
**only** use battle hardened captchas.

**Comment by tomleb** [comment]
Noted, I'll check what else we can do, like possibly just reload the page (with errors shown) instead of going to bad_captcha page.

**Comment by akuma06** [comment]
tomleb: You should do the way I did with Register page.
