### ISSUE TITLE
Eliminate empty spaces

### ISSUE THREAD

**Issue by tomleb** [NyaaPantsu/nyaa#383]
We want to eliminate empty spaces, especially vertical space.

Mostly looking at the mascot.
- [https://i.4cdn.org/a/1494563618108.png](https://i.4cdn.org/a/1494563618108.png)
I personnaly like this one.

**Comment by thewisenerd** [comment]
how about re-using the original nyaa layout? move the 'advanced search' options "categories" and "remake/filtered/a+" to the header to left of search bar; and have the search/sorting options in the header, to the right of the mascot?

thus, you can sort _any_ result, or page; regardless of a search;

**Comment by tomleb** [comment]
New link for the [image](https://desu-usergeneratedcontent.xyz/a/image/1494/56/1494563618108.png)

**Comment by akuma06** [comment]
#389 & #390 should have fixed a bit the problem, no?
