### ISSUE TITLE
Warn users about inaccurate/old seed counts

### ISSUE THREAD

**Issue by ripdog** [NyaaPantsu/nyaa#386]
There needs to be some way to inform users when (and if) seed counts last happened on a per-torrent basis. A lot of people seem to think that seed counts are live, so if there could be something like '(updated X hours ago)' or 'unknown seed count' close to the seed counter, I think that could correct those assumptions.

**Comment by egozi44** [comment]
Does it relate to the zero seed and leech I see on all torrents since page 2?

Yesterday the new seed count seem to work just fine, also when you try to download the torrent you get 404 error, but it probably only temporary

**Comment by akuma06** [comment]
The new torrents seed count are updated in a batch. So we don't have to run our scrapper for every single torrent uploaded.

**Comment by mitki** [comment]
Yeah I'm seeding some stuff from my seedbox yet 0/0, it's misleading since users check it before downloading.

**Comment by yiiTT** [comment]
Closed.
We now display unknown on the list page and the date the torrent was last scraped on the view page.

**Comment by egozi44** [comment]
It seem the date is now displayed in your home language rather than English, dk if I like that :/

the language is set to English in my profile but date still be in other lang
