### ISSUE TITLE
scraper

### ISSUE THREAD

**Issue by alucard0134** [NyaaPantsu/nyaa#403]
causes the main process to fuck up, i/o timeouts for days

**Comment by tomleb** [comment]
Was it not fixed with https://github.com/ewhal/nyaa/pull/394 ?

**Comment by SpaceDustTeapot** [comment]
We could have the scraper as a separate process.

**Comment by alucard0134** [comment]
it was not fixed, no

**Comment by tomleb** [comment]
I believe it already is running as a separate process.
Alucard, got any more info on the error ? I remember seeing logs of it, but lost them.

**Comment by majestrate** [comment]
it hits the database hard with bulk update transactions from multiple goroutines

the scraper already runs as a separate process and has from the start

**Comment by tomleb** [comment]
Woops in my head the issue was about rss feed

**Comment by akuma06** [comment]
Now that we have like all the scrapped data, would it not that be better to have it run only when you look a specific torrent. Of course, you check before that the seed/leech data is not fresh enough in the database.

So only torrents that have been looked recently will have fresh data. Then you can run a daily scrapping of the last 500 torrents that do not have up to date scrapped data.
500 being the number of torrents that we are sure doesn't crash the server for example.

You can also stop doing transactions and just creating all the queries and make a single big transaction with the query built. Or doing the same but every 20 torrents for example.

Anyway, that's just ideas to improve it, dunno how the scrapper actually work.

**Comment by lc-guy** [comment]
That fucks up sorting by seeders I think

**Comment by yiiTT** [comment]
Fixed?

**Comment by akuma06** [comment]
I think =)
