### ISSUE TITLE
RSS not validating

### ISSUE THREAD

**Issue by such-doge** [NyaaPantsu/nyaa#405]
The RSS feed is not validating. The closing link tag is interpreted as part of the magnet link and throwing an "invalid character in URI" error.

` <link>magnet:?xt=urn:btih:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF</link>`

I suggest enclosing the link data in `<![CDATA[  ]]>` tags like this:

` <link><!CDATA[magnet:?xt=urn:btih:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF]]></link>`

**Comment by yiiTT** [comment]
@such-doge what are you using to read the RSS feed?

**Comment by such-doge** [comment]
I just happened to use Feed Notifier while investigating a different issue, and it complains that it's not a valid feed. I used validator.w3.org to track down the actual error. In practice, torrent clients can handle the RSS feed just fine.

**Comment by akuma06** [comment]
The extension which uses the RSS is able to read easily from it and it uses simple javascript to parse it :)

**Comment by the-eater** [comment]
Currently the RSS is broken as the `<![CDATA[ ... ]]>` is now being written as `&lt;![CDATA[ ... ]]&gt;` since it's just thrown into the XML marshaller, you should be able to put 
```
`xml:",cdata"`
```

after the link definition to do this correctly

cc: @ewhal

**Comment by the-eater** [comment]
@sfan5 <3
