### ISSUE TITLE
账号系统不通用？邮件不发送

### ISSUE THREAD

**Issue by yamazakitouma** [NyaaPantsu/nyaa#421]
Nyaa和sukebei的账户不通用？sukebei现在也没法注册。

nayy注册后收不到验证email

**Comment by yiiTT** [comment]
Creating accounts on sukebei is disabled for now until the "Remove gorm" is finished you will be able to share accounts in a few days and more.

**Comment by LunarisDream** [comment]
能建立账号，可是验证email目前有些问题，可能暂时发不出去。没验证也依然可以登录。

**Comment by dqwyy** [comment]
My gmail doesn't recieve the confirm letter, either.
