### ISSUE TITLE
Flagging enhancement (or, I can't flag dupes, because I can't make them)

### ISSUE THREAD

**Issue by toynbeeidea** [NyaaPantsu/nyaa#433]
Thank you for adding the ability to flag duplicate/deprecated torrents.

There's a bit of a problem though:  I've been remaking all of my old torrents to remove nyaa.se and add new trackers, but I still can't upload them, because the old torrents are there and the system blocks me.  But I can't really flag the old torrents as "duplicates," because they aren't yet.

I could ask to "claim" my old torrents, but as I can't even edit current torrents once uploaded, that's useless for now anyway.  We wouldn't want to just let people edit trackers willy-nilly, that could lead to all sorts of unpleasantness.  

Perhaps a further flagging enhancement, like the ability to type in a note on the flag?  Then I could flag as dupe and say "Newer upload pending" or something?

**Comment by akuma06** [comment]
If you want to upload all your torrents again, you can just ask on irc that we remove them all for now or report the ones as duplicate with your account (we will see your username). 

I will look into that (if no one else have done it) in 2 days for adding the torrents management tool for users. Like editing your own torrents and editing the trackers of torrents in Bulk.

**Comment by toynbeeidea** [comment]
Okay, I've flagged a whole bunch of them, thanks!

**Comment by toynbeeidea** [comment]
So, uh... is this not gonna happen or something?

**Comment by toynbeeidea** [comment]
Knock knock.

**Comment by yiiTT** [comment]
@toynbeeidea Were you the one who reported some "PPP-RAW" torrents?

**Comment by akuma06** [comment]
Should be fixed with the torrent edit api
