### ISSUE TITLE
Make sukebei distinguishable

### ISSUE THREAD

**Issue by tomleb** [NyaaPantsu/nyaa#441]
Someone uploaded on sukebei instead of pantsu. I think we should make sukebei more distinguishable by changing the theme a little (maybe add a red tint) or something like that.

**Comment by nakedloli** [comment]
Also I think a logo for sukebei.pantsu.cat should be made

**Comment by dumbwanker** [comment]
Anyone got minimalistic pics of Ren-chon doujins?

**Comment by loadletter** [comment]
Maybe a vector of one of those
https://danbooru.donmai.us/posts/2107045
https://danbooru.donmai.us/posts/1581975

**Comment by akuma06** [comment]
A pink pantsu for sukebei @kipukun
