### ISSUE TITLE
Upload Image Embed / Text Editor

### ISSUE THREAD

**Issue by LightMonk** [NyaaPantsu/nyaa#444]
Simple Text Editor to add embed image codes etc. to the Torrent description?
Mashin for example usually put images into the description which is kinda missing right now.

**Comment by akuma06** [comment]
You can use markdown I think in the desc to add images and all. I've seen some torrents with images. But yeah, a markdown editor like https://stackedit.io/ would be a good improvement from nyaa

**Comment by yiiTT** [comment]
Added #572
