### ISSUE TITLE
Add more RSS fields

### ISSUE THREAD

**Issue by misuzu** [NyaaPantsu/nyaa#451]
Right now there is ```title```, ```link```, ```description```, ```guid```, and ```pubDate```.
nyaa.eu RSS also had ```category``` field.
[EZTV RSS](https://eztv.ag/ezrss.xml) have even more useful fields: ```torrent:contentLength```, ```torrent:infoHash```, ```torrent:magnetURI```, ```torrent:seeds```, ```torrent:peers```, ```torrent:verified```, ```torrent:fileName```.
Direct link to torrent file would also be great.

**Comment by ipatrol** [comment]
We should make sure to be compliant with the BEP standard for torrent RSS feeds: http://www.bittorrent.org/beps/bep_0036.html

**Comment by yiiTT** [comment]
#569 "Implement EZTV RSS Spec"
