### ISSUE TITLE
option to use night mode without js

### ISSUE THREAD

**Issue by lc-guy** [NyaaPantsu/nyaa#453]
title says it all

**Comment by majestrate** [comment]
how?

**Comment by akuma06** [comment]
Cookie?

**Comment by ZoneSix** [comment]
Set alternative attribute on the style link. Which makes it selectable from View > Page Style. Or for noscript users add a link to a server side script that adds a cookie which then is read by the server side script and serves the correct stylesheet.

**Comment by ayame-git** [comment]
this sounds potato af

**Comment by yiiTT** [comment]
if you want to change the night mode quickly JS is required. (don't over complicate things)
There will most likely be a setting in the account profile to change your whole account theme.
