### ISSUE TITLE
Move Renchon to the side / make her clickable

### ISSUE THREAD

**Issue by autismbux** [NyaaPantsu/nyaa#464]
As it is she's currently taking a lot of space. You could make better use of that by moving her to the side. I made a mockup:

![np](https://cloud.githubusercontent.com/assets/28681516/26031210/e052e84e-3838-11e7-8775-55d24aef30ea.jpg)

It'd also be fun to make the object clickable and say "Nyanpasu", as inspired by this site: http://nyanpass.com/

**Comment by aerojun** [comment]
I like it.

**Comment by yiiTT** [comment]
Works for me, and saves space on the top.

**Comment by CrowAU** [comment]
Looks good.

**Comment by tomleb** [comment]
Looks very good, where is the top pagination?

**Comment by mitki** [comment]
I can't see Renchon at all on my laptop (1366x768).
But it looks good indeed, way more clean.

![screenshot](https://f.lewd.se/GpnmIv.png)

**Comment by tomleb** [comment]
Maybe we could show the mascot under the torrent table (z-index) if the resolution is too low.
I'd suggest also adding the pagination back, make it centered and make it 10 instead of 5.
Can you do that and comment a new picture?

**Comment by autismbux** [comment]
New picture with tomleb's ideas

![np](https://cloud.githubusercontent.com/assets/28681516/26035104/ff9d9d00-3894-11e7-93b0-c85185ff44bb.jpg)

**Comment by tomleb** [comment]
Look very good imo, make a PR for that.

**Comment by autismbux** [comment]
uh, I think you misunderstand. I don't know go or have any experience in web design. I had an idea and made that image in an editor to post it on /g/. They then recommended that I post it here

I'm basically just the idea guy :^)

**Comment by tomleb** [comment]
No problem, thanks for your contribution, I'll see if I can make it myself in my design PR. :p

**Comment by nakedloli** [comment]
I recommend implementing #484 as well

**Comment by tomleb** [comment]
Hey autismbux, since you seem to be pretty good at design, got any suggestion for [https://github.com/ewhal/nyaa/issues/487](https://github.com/ewhal/nyaa/issues/487)?

**Comment by Senhart** [comment]
Spitballing a design as well. Made the top bar less thick, removed the no. of items next to the search bar, turned "Members" into "Login," moved the page navigators out of the white box, and rearranged the stuff below. I got the idea of an on and off switch for Dark Mode for #487. Not suggesting everything should be implemented, just throwing out ideas.
![image](https://cloud.githubusercontent.com/assets/13612267/26038562/fbc5e800-393d-11e7-853a-e77d45c78404.png)

**Comment by Yamozer** [comment]
![1495057955682 1](https://cloud.githubusercontent.com/assets/28688407/26178631/5f80a97a-3b5f-11e7-97e3-c18c4d10bc68.png)
Here's a higher res Megumin, in case you guys want to keep the night theme.

**Comment by kipukun** [comment]
This is done with #605 <3

**Comment by SleepingPanda** [comment]
Something is wrong here. The mascot is in the foreground for some reason. ![o_o](http://i.imgur.com/TW4hRqi.png).

**Comment by tomleb** [comment]
Indeed, I noticed that too. I'm no longer in charge of the UI.
I'll notify the guy in charge, we'll probably put the mascot in the background.

**Comment by kipukun** [comment]
This is fixed with #636! If you have a shit monitor, ごめん. I'll think about a way in which you can still see our cute mascots.
