### ISSUE TITLE
commenting on a sukebei torrent doesn't work

### ISSUE THREAD

**Issue by lc-guy** [NyaaPantsu/nyaa#494]
high-priority.
I was wondering why torrents were sometimes randomly disappearing (eg. wani ones). I experimented on 2 torrents, and they were both deleted. Don't want to try with more.

To anyone reading this issue, this isn't a bug with the current version of nyaa: it stems from the fact sukebei still runs on sqlite. It just requires the db to be moved to postgre

**Comment by nakedloli** [comment]
The torrent's aren't actually deleted, they're just hidden but are still in the data base

**Comment by alucard0134** [comment]
sukebei is currently on latest master HEAD. sukebei is still on a sqlite database, so the issue is with the sqlite portion of the codebase

**Comment by akuma06** [comment]
Now it doesn't work :/
