### ISSUE TITLE
option to auto-update every n (user-defined) seconds

### ISSUE THREAD

**Issue by CrisBRM** [NyaaPantsu/nyaa#497]
Title.
Should be default behaviour too.

**Comment by kipukun** [comment]
This would actually be easy to implement, with
``<meta http-equiv="refresh" content="5; URL=https://nyaa.pantsu.cat">``

**Comment by akuma06** [comment]
I don't think refreshing the whole page would be good for users and server. Better to use a XHR request on /api and add the new torrents

**Comment by akuma06** [comment]
Should be fixed in #842
