### ISSUE TITLE
Menu style issue

### ISSUE THREAD

**Issue by akuma06** [NyaaPantsu/nyaa#507]
Fix from @sfan5 doesn't seem to work with pseudo of 7 characters.
https://puu.sh/vQ13t/43017ce39d.png

Two possibilities:
- We push further margin-right (-100px or -8rem)
- We move the search bar (the select button for maximum item showed doesn't provide enough information on what it does btw)

Downside: 
- First proposition makes the badgemenu disappear on little screen
- People are used to have the search bar in menu, so moving everything out would be counterproductive.

**Comment by nakedloli** [comment]
Where do you plan on moving the search bar?

**Comment by sfan5** [comment]
Just move it a few more pixels to the right
¯\_(ツ)_/¯

**Comment by mitki** [comment]
Related https://github.com/ewhal/nyaa/issues/427.

**Comment by akuma06** [comment]
I plan nothing. Just opened the issue so you can discuss things :p

**Comment by kipukun** [comment]
This is no longer an issue in the latest dev.

**Comment by kipukun** [comment]
![capture](https://cloud.githubusercontent.com/assets/6733106/26158742/a17984f2-3aea-11e7-91d0-c25a95067af1.PNG)
