### ISSUE TITLE
New Style Mockup

### ISSUE THREAD

**Issue by ripdog** [NyaaPantsu/nyaa#512]
gjwufq3x from #nyaapantsu-dev got bored one day and mocked up a really nice new design.
![2za7ft](https://cloud.githubusercontent.com/assets/174944/26038538/bfafb758-395e-11e7-80e0-31f4a063001c.png)
He also uploaded a skeleton of his design here: https://a.pomf.cat/qzyhky.7z

Thoughts? Volunteers for implementing?

**Comment by aerojun** [comment]
Looks pretty cool to me. The only thing i don't like is the table using all the with, leaving no space for #464

**Comment by mitki** [comment]
I think the header looks so great.

**Comment by newtonseple** [comment]
Way too few torrents per page tho

**Comment by tomleb** [comment]
Yeah too few torrents per page. It does look good, but I don't think old people of nyaa would like this new theme, so I am personally against using it. (Unless we make it a different theme, aka not the default one)

**Comment by LL-LLS** [comment]
@tomleb 
I don't understand, why old nyaa user not accept new interface.
This UI both beautiful and practical, i accept this theme.

**Comment by tomleb** [comment]
In its current state, it's not practical. 10 torrents per viewport, navbar taking 1/4 of screen.
It's just not. Also, we want to keep people using our website, and those people are coming from the old nyaa and are somewhat expecting a similar experience / design. Changing the default theme would be a big risk to take and I'm not ready to take that risk. (I'm not the project leader though, I'm just saying my opinions)
Making it as different theme that you can select is good enough. We don't frustrate people that likes the previous theme and people that want to use this theme could easily do so by changing the theme.

**Comment by LL-LLS** [comment]
If you say every torrents per number, this is demo version.
Whether it is torrents per or page number, can be increased.

**Comment by tomleb** [comment]
Sure, but then my second point still applies.

**Comment by LL-LLS** [comment]
I accept different theme, just like the current NightMode.

**Comment by egozi44** [comment]
Any chance that rather than new design you could just add theme or colors to the page and background?
the page is white and mix up with the commits window

![jghjgh](https://cloud.githubusercontent.com/assets/14190834/26083127/97e9d144-39dc-11e7-84dd-94072e0735b1.PNG)

**Comment by aerojun** [comment]
@egozi44 yeah, no problem.

**Comment by egozi44** [comment]
Thanks

**Comment by watchoutfortanelidaizvatanenthepublicen** [comment]
/g/ version
![edit7c](https://cloud.githubusercontent.com/assets/28690699/26121689/62b9b39c-3a75-11e7-94df-e5938fd47ad6.png)

**Comment by yiiTT** [comment]
track the progress at #658
