### ISSUE TITLE
Increase http.server Timeouts

### ISSUE THREAD

**Issue by yiiTT** [NyaaPantsu/nyaa#517]
The current settings are a fairly low value for timeouts (5/5), and the "standard" in go that people are using from what I found were 0/0, 10/10, 10/5. ([cloudflare's Go guide](https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/) has 10/5).

We get about 70 RPS live and these tests are at 400 RPS without any nginx/varnish cache on ansible production deployment + PostgreSQL 9.6 + Nginx proxy_pass.
These are direct hits to my test server on the frontage and don't resemble normal usage.

Command: "ab -n 4200 -c 400 http://localhost"
WriteTimeout: 5 / ReadTimeout: 5 
https://a.uguu.se/puLewTsCRIbH_2017-05-14_21-05-00.mp4 - [stats](http://i.imgur.com/GWK6qiY.png) 

WriteTimeout: 30 / ReadTimeout: 10
https://a.uguu.se/3WqzvRrztdmy_2017-05-14_21-08-53.mp4 - [stats](http://i.imgur.com/zc9ERnu.png)

----
Proposed Changes
```
WriteTimeout: 30 * time.Second,
ReadTimeout: 10 * time.Second, 
```

Changes People have made to the timeouts:
https://github.com/ewhal/nyaa/commit/e6f55ec0614d7c49be7fa282b2276ac71f850771
https://github.com/ewhal/nyaa/commit/105e178031c256fd01a22f1c202762a0b170175b

**Comment by sfan5** [comment]
This is desperately needed to make torrent reassigning work correctly.
Anything over 250 torrents doesn't work because of the timeout...
