### ISSUE TITLE
Advanced search syntax

### ISSUE THREAD

**Issue by autismbux** [NyaaPantsu/nyaa#525]
One of the best things about the old Nyaa was its flexible search engine. It allowed you to use various operators to help further refine your searches. I'd like to see the same functions brought back

**Exclude words**
ex: *shingeki -bahamut*
This would filter out "bahamut".

**X or Y**
ex: *kyojin|bahamut*
Results that contain either "kyojin" or "bahamut".

**Exact match**
ex: *"shingeki no"*
Only results that contain the string "shingeki no".

I believe there were more but these are the ones I can recall for now, and probably the most useful.
On a semi-related note, the engine ought to be able to search by user directly from the profile instead of having to click "See more torrents from [user]". For example, if I go into [HorribleSubs' profile](https://nyaa.pantsu.cat/user/14/-) and I search for something, the resulting url should already include "userID=14" instead of "userID=0"

**Comment by sfan5** [comment]
duplicate/related #234

**Comment by autismbux** [comment]
Oh my bad. I think the second thing's been brought up though
