### ISSUE TITLE
Exclude torrents in search by user id.

### ISSUE THREAD

**Issue by Flaminator** [NyaaPantsu/nyaa#528]
On the old site there was an input field to hide torrents by user id, this is sadly missing from the new site. This was one of the features I used the most because it helped remove all the clutter of all the HorribleSubs releases.

**Comment by yiiTT** [comment]
Ahh yes like a global filter on your account, I've talked to a few people who have also been missing this feature to filter out HorribleSubs or other groups they don't want releases from.

**Comment by Flaminator** [comment]
Well on the old site I didn't have an account, so it was just an input field above the release list together with begin and end date fields I believe.
