### ISSUE TITLE
line breaks in column titles

### ISSUE THREAD

**Issue by moose65468** [NyaaPantsu/nyaa#564]
For some languages (ex. japanese) there are line breaks in the column titles:
![0000001](https://cloud.githubusercontent.com/assets/28694152/26131799/0edb5650-3a51-11e7-94c0-bd528ebdaedc.PNG)

This can possibly be fixed by adding `.col-xs-1 {white-space:nowrap;}` to /public/css/style.css resulting in: 
![0000002](https://cloud.githubusercontent.com/assets/28694152/26131860/610338ee-3a51-11e7-8627-9a5f326f4113.PNG)

Unfortunately, this still leaves line breaks in the chinese translations between the magnet and torrent links:
![0000003](https://cloud.githubusercontent.com/assets/28694152/26132830/bd117ba4-3a57-11e7-84af-83dbc6e68693.png)
Perhaps by also changing line 54 of  /templates/home.html from: 
`<td class="hidden-xs">` 
to:
`<td class="hidden-xs" style="white-space: nowrap;">`
this can remove these line breaks without breaking the other columns: 
![0000004](https://cloud.githubusercontent.com/assets/28694152/26132835/c7410ae0-3a57-11e7-9403-9c2a44d0790c.png)
I've only tested this through my browser's editor, though.

**Comment by yiiTT** [comment]
Yup looks like that last one fixed it, it should get pushed onto the live server in the next days or so.
