### ISSUE TITLE
Tracker udp://tracker.doko.moe:6969 doesn't track stats

### ISSUE THREAD

**Issue by Darkmeep** [NyaaPantsu/nyaa#567]
I'm sure this is fairly obvious but all the files made with udp://tracker.doko.moe:6969 show 0 /0/0 in on the site.

**Comment by ElegantMonkey** [comment]
Are you sure? Probably the tracker scraper is just down, seeing that every recent torrent is 0/0/0.

**Comment by Darkmeep** [comment]
Not sure if I used the wrong term but yeah it's working as a tracker in torrents but the scraper is it? Isn't working

**Comment by ElegantMonkey** [comment]
There's an issue with the scraper causing problems with the web server, as reported on #403. It's turned off right now, I guess.

**Comment by yiiTT** [comment]
The scraper has been running for the past ~6 hours, It was just not re-started after deploying an update.
