### ISSUE TITLE
Sorting by seeds when all relevant returned have 0 seeds returns empty list

### ISSUE THREAD

**Issue by rschwiet** [NyaaPantsu/nyaa#570]
Currently if a search term yields valid results (but none have seeds) then sorting by seeders returns an empty page.  Feel like it'd be less confusing to just maybe return the same page or maybe have some other indicator that you ARE sorting by seeds and the maximum seeds is 0.  Not sure if this is a bug or a design choice though.  Either way I feel like it should be changed.

**Comment by akuma06** [comment]
Should be fixed
