### ISSUE TITLE
Inconsistent indentation in *.css and *.js files

### ISSUE THREAD

**Issue by goonyaa** [NyaaPantsu/nyaa#583]
Looking at
https://github.com/NyaaPantsu/nyaa/blob/dev/public/css/style.css
https://github.com/NyaaPantsu/nyaa/blob/dev/public/js/main.js

I guess some formatting styleguide should be used.

**Comment by ayame-git** [comment]
>open source

**Comment by kipukun** [comment]
We could easily setup a pre-commit hook to format all code: Go, HTML, CSS, and JS
