### ISSUE TITLE
[Wishlist] Don't limit RSS items (current limit is 50)

### ISSUE THREAD

**Issue by junpet** [NyaaPantsu/nyaa#587]
Old nyaa has no limit or a very high. Once I was away for three days, I got ~180 items.

**Comment by akuma06** [comment]
/feed?max=200 should give you 200 elements. You can change it to your likings. And if you use something like feedler for your rss, you will have an history

**Comment by junpet** [comment]
Thanks for the tip.
I use offline reader, because none of the online ones store that much feed what I need (for free).

**Comment by junpet** [comment]
@akuma06  It looks like "/feed?max=200" doesn't work, I still got only 50 feeds. :(
