### ISSUE TITLE
Hard to see text in markdown editor with night mode on.

### ISSUE THREAD

**Issue by goonyaa** [NyaaPantsu/nyaa#588]
On latest dev branch.

textarea active
![screenshot_2017-05-17_23-25-28](https://cloud.githubusercontent.com/assets/892135/26174500/44baa336-3b58-11e7-8578-0cf4aa2af599.png)

textarea not active
![screenshot_2017-05-17_23-25-21](https://cloud.githubusercontent.com/assets/892135/26174515/51827742-3b58-11e7-87d9-957feb698503.png)

**Comment by sfan5** [comment]
@yiiTT pls

**Comment by akuma06** [comment]
Should be fixed
