### ISSUE TITLE
[minor] js TypeError when logged in

### ISSUE THREAD

**Issue by goonyaa** [NyaaPantsu/nyaa#590]
Steps to reproduce:
- open console when logged in

Makes sense because we don't show language select form for logged in users.
![screenshot_2017-05-17_23-50-12](https://cloud.githubusercontent.com/assets/892135/26175655/04f6bcea-3b5c-11e7-8397-1fd7f0954eb5.png)

**Comment by aerojun** [comment]
Language selector is missing when logged in. That's why.
![screen shot 2017-05-17 at 3 59 52 pm](https://cloud.githubusercontent.com/assets/709320/26175910/edb76b48-3b19-11e7-8a32-83184e5d0464.png)

**Comment by akuma06** [comment]
Should be fixed
