### ISSUE TITLE
Sometimes mode switcher disappears

### ISSUE THREAD

**Issue by goonyaa** [NyaaPantsu/nyaa#595]
![screenshot_2017-05-18_00-42-26](https://cloud.githubusercontent.com/assets/892135/26177678/55db60dc-3b63-11e7-9cff-550abb40a94f.png)

**Comment by akuma06** [comment]
It's not a bug, I think it's wanted

**Comment by kipukun** [comment]
PR #581 is changing the button around, so this can be worked on once we see that pulled.

**Comment by goonyaa** [comment]
@akuma06 if it works as intended I'm fine with it. Just feels a bit strange.
@kipukun my bad, did not look at that PR.

I guess, guys, you should close this issue than.

**Comment by kipukun** [comment]
@goonyaa All good friend. We'll see if it still applies once it merges. Or we can just update this issue if an issue still applies to the night/day button.

**Comment by akuma06** [comment]
@goonyaa  Dunno if it is good to let it like that. I was just pointing out that it was thought like that (surely for having more space on the navbar for the search form)
