### ISSUE TITLE
Long username destroy the look of navbar

### ISSUE THREAD

**Issue by tomleb** [NyaaPantsu/nyaa#597]
![long name](https://my.mixtape.moe/vycqfo.png)
The navbar needs work.
Need to remove IRC link (put it in FAQ).

**Comment by kipukun** [comment]
Removed IRC link in #605 but still need to deal with this. Probably a dropdown search bar?

**Comment by SandroHc** [comment]
Either way, long usernames should still be trimmed. Anything above 15 characters, maybe?

**Comment by mitki** [comment]
The avatar is so big imo, and gravatar isn't privacy friendly.

**Comment by kipukun** [comment]
@SandroHc I could possibly create a username box and have the username just ellipses if it's too long. But there really should be a char limit in the backend.
@mitki I agree. Fixing soon (tm)

**Comment by steindornatorinn** [comment]
@kipukun There already is a 20 character limit in place, it's just that there isn't enough space on the sidebar to keep all of it.

I want to move the night mode button as suggested in #487, as it's not very well designed or implemented in it's current state. This would leave just enough space for it to work as intended on normal sized devices.

**Comment by kipukun** [comment]
@steindornatorinn I'm rewriting the entirety of the HTML. Any current HTML or CSS issues will most likely be null and void by the time I'm done.
