### ISSUE TITLE
NyaaPantsu doesn't seem to work

### ISSUE THREAD

**Issue by akuma06** [NyaaPantsu/nyaa#616]
I have this error from Chrome "NET::ERR_CERT_COMMON_NAME_INVALID" on all my computers/phone when I want to access to nyaa.pantsu.cat .

Already flushed my dns, emptied my cache and tried on different wifi router. So I don't think that's me :)

EDIT : 
Here are the ssl test from another third party website : https://www.ssllabs.com/ssltest/analyze.html?d=pantsu.cat
https://www.ssllabs.com/ssltest/analyze.html?d=nyaa.pantsu.cat
They say, they can't resolve domain name

**Comment by akuma06** [comment]
Add link : 
http://www.isitdownrightnow.com/nyaa.pantsu.cat.html
Seems down for everyone

**Comment by Albirew** [comment]
problem seems to be because HSTS is activated with a self-signed certificate.
Admin needs to either deactivate HSTS or change SSL certificate to a recognized one (letsencrypt for example).

**Comment by pantsuisdying** [comment]
週刊少年マガジンをリスティングしたからこうなったんだよ。
最初は、週刊少年ジャンプを一旦リスティングした後で消してたよね？
あの時、警告したはずだが。
nyaa.siに勝ちたかったのかもしれんんが…調子にのるなクズ。
閉鎖してもリアルで追い込んでやっからならゴミチャイナｗｗｗｗｗｗｗｗｗｗｗｗｗｗｗｗ

**Comment by mitki** [comment]
https://nyoo.moe/ is working fine tho.

**Comment by aerojun** [comment]
The server is responding. Maybe it's a bad configuration?

**Comment by toynbeeidea** [comment]
I'm getting a slightly different error:

```
nyaa.pantsu.cat uses an invalid security certificate.

The certificate is not trusted because it is self-signed.
The certificate is only valid for Plesk

(Error code: sec_error_unknown_issuer)
```

Not for nothing, but its quite simple to install certbot (https://certbot.eff.org/).  I use it on my own server.

**Comment by yiiTT** [comment]
The issue has been solved, there was a problem on the domain registrar end that we could not fix. We are now waiting for Cloudflare to issue a SSL certificate.
