### ISSUE TITLE
Add UptimeRobot badge to Readme?

### ISSUE THREAD

**Issue by dumbwanker** [NyaaPantsu/nyaa#617]
Can a [UptimeRobot](https://uptimerobot.com) badge for nyaa.pantsu.cat and nyoo.moe be added to the readme, so people can see if the sites are up or not?

Adding them seems quite simple. Create an account, add a new monitor for each site, go to My Settings, API keys, Monitor-specific, create a key for each site and add the following to the readme

`![](https://img.shields.io/uptimerobot/status/MONITOR_KEY.svg)`

Would do myself, but I don't want to receive an email every time the site goes down

**Comment by toynbeeidea** [comment]
To what end?  If you try to access the page and can't, its down.  If you can, its up.

**Comment by dumbwanker** [comment]
Well, you know if it's down for everyone or if there's something wrong on your end, without having to go to downdetector or something

**Comment by ewhal** [comment]
Not needed
