### ISSUE TITLE
Long torrent names get messed up with comment badge

### ISSUE THREAD

**Issue by kipukun** [NyaaPantsu/nyaa#618]
![](https://my.mixtape.moe/opojlt.png)

**Comment by goonyaa** [comment]
Why not make comment number as separate column in first place?

**Comment by kipukun** [comment]
@goonyaa That's what I'm planning on, but do we really need it? 🤔

**Comment by goonyaa** [comment]
@kipukun Anon asked about it. Old nyaa had it. And we, actually, already have it.

**Comment by mitki** [comment]
Truncate the torrent name in a responsive way seems elegant, or maybe just put the comment number as a tooltip, it isn't an important info.

**Comment by kipukun** [comment]
+1 to tooltip. Will make a PR soon.

**Comment by yiiTT** [comment]
Why are we limiting the space we use to display information in the first place? Once you get to a certain screen size it should take up a percentage and not a fixed width.

EX: ![](http://i.imgur.com/jNIFchh.png)

**Comment by kipukun** [comment]
@yiiTT 
That size is kind of unrealistic. I've been working on a 1080 monitor, and I think 4K would work fine as well. Though I do agree having it as a fixed size is bad style, the example is kind of far fetched.

**Comment by akuma06** [comment]
Comments number are really a thing. When I download a torrent, I usually look on the number of comments (real popularity) and Seeders. :p

**Comment by kipukun** [comment]
I'll just make another column. 
![](https://s-media-cache-ak0.pinimg.com/736x/0c/ec/d5/0cecd5ac5e9347098932e00362a0bbc3.jpg)
