### ISSUE TITLE
Another few things suggestions about the site

### ISSUE THREAD

**Issue by egozi44** [NyaaPantsu/nyaa#619]
Well most of them been talked about few times but seem to be forgotten/lost with all the other threads

1.  will you add the File preview option in the future? so far Nyaa.si have it and it seem to work pretty much alright.

2. Subaki should have different logo and background as the site so far look identical to the normal nyaa and even identical to Nyaa.Si which can confused people (Also load times are still a bit slower and if you press the "Fun/fap" Buttons it can sometimes can take few seconds till it direct the user to the site)

3. Add "Remember me" button to the log in menu and fix the email verification (never got mine yet still was able to create user but it may have it own backfire in the future...)

4. Add more features to the User profile menu such as subscribe option (It was really helpful in old nyaa)
    
5. Downalod torrents button will randomlly work or will give 404 error (depend on your daily changes I guees? xD), could you fix it?

6. Optional.... will it be possible to change "れんちょん" back to "anonymous"?  xD
It can confuse people who didn't read the FAQ (unless that was your plan all along)

**Comment by yiiTT** [comment]
1. Already added, it's just below the description

2. There has been some talks like changing the mascot and we can always improve the looks. If you have any suggestions on how you feel like it should look we are always taking things into consideration. There is even an updated theme that still needs to go on live but we still should distinguish nyaa and sukebei a bit more. 

3. The current way cookies work is that if the server restarts the cookies are all cleared, these are "Stateless Cookies". There has been some talks about this and It would be nice to stay logged in between restarts and what not.

4. If I remember correctly there is already the functionality of this feature it just has to be fully implemented.

**Comment by egozi44** [comment]
Was editing my commit few times while you replyed (sorry for the trouble)

So we won't be able to stay log in like... forever? I know that purchase sites usually do it for various reasons but does torrent site really need it? (it more annoy if anything else >.> )

As for the mascot... I can try think on few stuff

**Comment by yiiTT** [comment]
> So we won't be able to stay log in like... forever? I know that purchase sites usually do it for various reasons but does torrent site really need it? (it more annoy if anything else >.> )

Well the reason you are not staying logged in, is less of you logging out and more of US updating the main server with a new version or moving servers like we did ~16 hours ago. I do agree with you that we should have statefull cookies.

**Comment by egozi44** [comment]
> Well the reason you are not staying logged in, is less of you logging out and more of US updating the main server with a new version or moving servers like we did ~16 hours ago. I do agree with you that we should have statefull cookies which would keep you logged even after restarts or server migrations.

Oh I see, it pretty much reasonable reason.

**Comment by yiiTT** [comment]
The issue of the downtime from today was when we moved our domain to a different registrar which then had conflicting nameservers so it could not properly resolve how to get to *.pantsu.cat. All we could do is wait for the registrar's support to fix the issue, but luckily we still had http://nyoo.moe until the issue could be resolved.

When we move servers you probably wont notice much other than being logged out most of the time.

**Comment by sfan5** [comment]
3. Cookies are actually valid for a week (if no new version is deployed), but yeah a proper Remember Me option should be added

5. Newer torrent file are only available if the uploader provided one and older torrent files are (currently) only available for up to 2 years back.

6. Not having the usual boring `Anonymous` is a nice touch and I don't think this should be changed.

**Comment by egozi44** [comment]
Well hopefully you will add Remember Me button one day~

As for the anonymous thingy, it may be indeed refreshing but if you taking other users/people into account it may be confusing, let say that some uploader decide to register in the same name or really similar name, and users who don't know/don't used to Japanese will just mistake him to れんちょん (which is anonymous), it just confused them, well anyway the choose is up to you, I just suggesting things~


Oh and I noticed the File preview is missing from Sukebei, but that probably just because it WIP

**Comment by akuma06** [comment]
1. done
2. done
3. done and still need @ewhal to configure emails account
4. done
5. done
6. need to be a separate issue for discussion as @yiiTT said

**Comment by egozi44** [comment]
Nicu,

As you said there's still not remember me button till ewhal configure it
So far nice work.

I don't sure why we need new issue for anonymous status if you want I will go ahead and will make one...
