### ISSUE TITLE
Issue with Uploading Torrentfile?

### ISSUE THREAD

**Issue by LightMonk** [NyaaPantsu/nyaa#628]
Added Yamato 2202 Torrents have issues loading the Metadata from the Magnetlink:
https://nyaa.pantsu.cat/view/924238
When downloading the Torrentfile it loads fine.
I only uploaded the Torrentfile while I kept the Magnetlink textbox empty (as I thought I won't need to fill it when I already upload a Torrentfile)
Not sure if its only me.

Other thing:
The Torrentfile didn't had the Torrentname I uploaded it with or added with the Torrentname.

**Comment by sfan5** [comment]
If a torrent doesn't download using a magnet link that usually means nobody of the seeders is connected to the DHT or any of the trackers that are included in the magnet link.

**Comment by LightMonk** [comment]
Is there a reason wh the Magnetlink is not working the same way the Torrentfile does?
Can that be solved during the upload?
Now that I know that I need to download the Torrentfile if it doesn's load it doesn't concern me much but its still fairly annoying.

**Comment by akuma06** [comment]
It can't magnet link doesn't work that way as explained by @sfan5
