### ISSUE TITLE
Log in with no password leads to white screen

### ISSUE THREAD

**Issue by ChaoticKrisis** [NyaaPantsu/nyaa#634]
When you log in and leave the password field empty it redirects you to a white screen indefinitely.
When trying to refresh it says "The page that you're looking for used information that you entered. Returning to that page might cause any action that you took to be repeated. Do you want to continue?"

**Comment by tomleb** [comment]
I'm getting a white screen on dev too (no error shown), I'll see if I can fix this to at least alert the user.
