### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by justrossthings** [NyaaPantsu/nyaa#647]
Hi I'd like to take on some frontend tickets. What is the process for taking on a ticket in the Trello backlog/in progress?

**Comment by ewhal** [comment]
Pretty much just work on whatever.

**Comment by akuma06** [comment]
If you think you can't make it quickly, you can commit the first changes with a (WIP) attached to the commit name. So everyone know that you work on it

**Comment by justrossthings** [comment]
Thanks. I made this: https://github.com/NyaaPantsu/nyaa/pull/651
