### ISSUE TITLE
Completely refactor HTML/CSS/JS

### ISSUE THREAD

**Issue by kipukun** [NyaaPantsu/nyaa#658]
## Summary
We currently have a problem with the frontend being too bloated, and too boiler-platey. At first, I considered rewriting from scratch with a CSS frame work such as PureCSS, but seeing the breadth of the project, that would simply be too time consuming to be viable.

**EDIT:** _After a nice long shower, I think a rewrite would be feasible. Of course it would require a complete overhaul, but it will be beneficial in the long-run. Wish me luck!_ 

Rather, I think it would be much more beneficial to completely go over the current frontend code we have and refactor. This would improve the following:

- Formatting issues. Using tabs consistently, and having proper indentation for readability.
- More efficient Javascript. The minimal amount of JS we have should be as lean and fast as possible. 
- More semantic CSS class and id names. This would make it much easier to theme in the future, as it seems that's where we're going with CSS. 
- Neater HTML, which should fully utilize HTML5 semantics (i.e, as minimal divs and spans as possible).
- Combining HTML templates where possible, with minimal reuse of code. 
- **Comments, comments, comments.** This is VERY important, and we are lacking in a lot of departments. 
- **Speed.** The website should be as slim and trim as possible. This ties into the first five issues.

## Redesign 
There have been much, much talk about a redesign, using mockups by designers. Everyone seems to really enjoy the look of them, and I do as well.However, fixing the above issues should come first, and a redesign later. The issues highlighted above are arguably much more important than how something looks. **Functionality over aesthetics is the goal currently.** Once there is a solid base as to work off of, themes and redesigns will be more viable. That doesn't mean we shouldn't do a redesign, but that should be last on the list.

### Contributing
If you would like to help me with this, there will be a "frontend-rewrite" branch on my fork. Feel free to fork my fork and send pull requests.

**Comment by nakedloli** [comment]
Looks like the thread anon would like to help you out https://boards.4chan.org/g/thread/60502835#p60506091

**Comment by alucard0134** [comment]
~~

**Comment by transifex3** [comment]
#132 hope no-javascript option would be one of options as well

**Comment by kipukun** [comment]
@transifex3 As it stands right now, the site stands on **absolutely no external CSS or JS.** All of it is in house. The site is fully functional without JS.

**Comment by yiiTT** [comment]
Mascot breakpoints "1200px to 1500px/1470px is when the mascot should not show, with 1470px their arm/staff almost touches the category icon and looks fairly good."

**Comment by kipukun** [comment]
I'm closing this as the refactor is technically done. All small issues are to go to #755.
