### ISSUE TITLE
Allow only text in comments

### ISSUE THREAD

**Issue by tomleb** [NyaaPantsu/nyaa#659]
I think we should disable all markdown in the comment section. Only text should be allowed because the markdown can be abused such as [here](https://nyaa.pantsu.cat/view/488386) which makes the browser go super slow.
I don't think markdown adds anything to the comment section.
(Also, we need to moderate the comment section of the link above.)

**Comment by yiiTT** [comment]
This is normal back then, xDev had a few torrents that were hidden like this.

**Comment by tomleb** [comment]
So what do you suggest then ? We don't have a mod team yet afaik.

**Comment by nakedloli** [comment]
We do

**Comment by steindornatorinn** [comment]
I think the problem here is displaying 1000+ comments in one page, and not the markdown per-se.

**Comment by yiiTT** [comment]
Well it's not like this kind of torrent is common. You don't normally see more than what 15 comments on a torrent.

So given rarity of this issue I don't think it really need to be addressed.
