### ISSUE TITLE
Multiple user torrents pages

### ISSUE THREAD

**Issue by c0tangent** [NyaaPantsu/nyaa#676]
There are currently multiple pages which show a user's torrents:
* https://sukebei.pantsu.cat/user/3750/- (user profile, linked by clicking on a username on a torrent)
* https://sukebei.pantsu.cat/user/3750/mikocon (user profile, linked by clicking the "Torrents" under the gravatar on a user profile)
* https://sukebei.pantsu.cat/search?userID=3750 ("See more torrents from user" page)

This is duplication of functionality that would simply confuse users and devs. For example, clicking on RSS on the "user profile" page does not give the RSS feed of the user, but of the whole site. Clicking the RSS button only functions properly on the "See more torrents from user" page.

We should simply merge the two pages together, either by providing pagination on the user profile page or getting rid of the user profile page.

**Comment by akuma06** [comment]
1 shouldn't be a thing anymore
2 and 3 are intended, it's more like a youtube page. You have the latest torrent on the profile page and if you want everything: "more torrents". I intended to add more "thing" to the profile page, like a website link, irc link, some user description and (if allowed in settings) his number of followers and his followings

**Comment by ElegantMonkey** [comment]
Also, there currently is a user RSS button on the profile (see #674), however I agree that the navbar RSS link should give the user RSS feed on the profile page, and not the entire website feed. I'll look at it.
