### ISSUE TITLE
Suggestion: BBCode support

### ISSUE THREAD

**Issue by ShardM** [NyaaPantsu/nyaa#687]
Hello and thanks for the new site.

Why not support BBCode as everyone from Nyaa already knows it and also it is more versatile. It allows spoiler tag, text positioning (center, left ect), more control on sizing and text coloring.

**Comment by yiiTT** [comment]
I was thinking about converting BBCode to markdown once it gets sent to the server.

**Comment by ShardM** [comment]
If it converts it to markdown, wouldn't it remove some of the formating as BBCode has greater number of formatting.
