### ISSUE TITLE
Mascot covers torrents table

### ISSUE THREAD

**Issue by sfan5** [NyaaPantsu/nyaa#691]
This happens at 1366x768 which I would not consider ''<i>too small</i>'' to realistically fit the content
![bildschirmfoto_2017-05-23_01-48-50](https://cloud.githubusercontent.com/assets/1042418/26332912/2c69bb54-3f5a-11e7-8057-ef69991f693e.png)

**Comment by yiiTT** [comment]
1200px to 1500px/1470px is when the mascot should not show, with 1470px their arm/staff almost touches the category icon and looks fairly good.

**Comment by lc-guy** [comment]
Can't mascot just be below the table?

**Comment by yiiTT** [comment]
to be fixed in #658
