### ISSUE TITLE
Consistent type for ID's

### ISSUE THREAD

**Issue by tomleb** [NyaaPantsu/nyaa#693]
I think we should have consistent ID's type. Currently the id is integer for Torrent and string for TorrentJSON. In some functions for the database they accept a string as ID. Id's are integers in postgres.
Imo we should have a consistent type for ID's (uint64)

I'm not sure of the impact of changing the id in TorrentJSON to integer, it could break some script that uses our API.

**Comment by Atvaark** [comment]
64-bit integers aren't exactly compatible with JSON (since JavaScript clients can only use 53-bit integers).

**Comment by akuma06** [comment]
I think most of it has been changed to uint. Please @tomleb check and close :)

**Comment by Kiloutre** [comment]
can it be closed?
