### ISSUE TITLE
Strip <li> from comments and descriptions

### ISSUE THREAD

**Issue by yiiTT** [NyaaPantsu/nyaa#701]
Allowing the usage of `<li>` tags can break the HTML on the page since they need to be surrounded by `<ul>`. Strip out any `<il>` tags and require them to use markdown lists if they want to make lists or design the HTML and CSS not to escape out it its container.

Other than the li tag every other HTML element that is allowed under the UGCPolicy works and displays fine in HTML and markdown.

![](http://i.imgur.com/gdO2IJN.png)

**Comment by sfan5** [comment]
There's a quite general problem here, we shouldn't be allowing HTML in comments even if it is done safely.

**Comment by yiiTT** [comment]
Hmm well a large issue would be sites that don't support markdown quick code and just provide the HTML or most of the time BBCode for uploaders and I've seen the issue myself. 
We are already limiting what kind of tags and attributes they can use and everything that you can do in HTML you can do in markdown so there is no difference just another way of formatting it.

Also simple BBCode should be converted to markdown, but Ill make another issue for that.

**Comment by akuma06** [comment]
Should be fixed by #718
