### ISSUE TITLE
Bug: Images not appearing

### ISSUE THREAD

**Issue by ShardM** [NyaaPantsu/nyaa#714]
https://sukebei.pantsu.cat/view/2305412

Above link is a torrent I created and the images appeared fine in the preview but didn't appear when published.

**Comment by sfan5** [comment]
I've seen this a lot of times now, problem with markdown editor?

**Comment by akuma06** [comment]
It would great to know what is displayed in the database for the bug. So we know if it comes from the insert or the renderer

**Comment by akuma06** [comment]
Should be fixed with the new markdown editor
