### ISSUE TITLE
on:hover cover mascot

### ISSUE THREAD

**Issue by darkash** [NyaaPantsu/nyaa#716]
![image](https://cloud.githubusercontent.com/assets/2842880/26373383/9046c2e4-402b-11e7-80db-d5a3395bef03.png)

i don't think this look nice since with how the face is cut off by the zooming in of the table row, or is it the expected output?

Not sure if this info is needed, but here anyway.

tested browser with this output:
Opera version 	45.0.2552.812
Firefox 53.0.3

used OS:
Windows 7 32-bit

**Comment by ElegantMonkey** [comment]
Setting `z-index` to a high number (10 works for me) on the mascot seems to fix it, although I don't know why this happens. @kipukun?

**Comment by kipukun** [comment]
Hey everyone! Currently, the HTML and CSS is being completely rewritten, so this issue won't happen in the next release, I promise! <3

**Comment by yiiTT** [comment]
to be fixed in #658
