### ISSUE TITLE
Suggestion: Option to exclude additional trackers

### ISSUE THREAD

**Issue by ShardM** [NyaaPantsu/nyaa#717]
When add a torrent with e-hentai tracker, you really do not want to remove it or replace it. You are trying to tally up download points for credits. When you download it through the magnet it removes e-hentai and adds its own.

**Comment by yiiTT** [comment]
Ahh you mean something like take the trackers from the torrent file and append it to the magnet link.
Yes this needs to be done to allow support for other trackers.

**Comment by ShardM** [comment]
Yes, that's the one. Why does it then remove the uploaders tracker(s). Surely that is the most important one. Can't you just add to the existing trackers in the torrent?

It kinda of makes it pointless to uplaod e-hentai files as it bypasses the tracker. Does it not?

**Comment by sfan5** [comment]
While it might seem so nothing gets "removed", we simply don't extract the trackers from torrent file (yet). Thus the magnet links use a default set of trackers which in some cases will obviously differ from ones that should be there.

**Comment by yiiTT** [comment]
> It kinda of makes it pointless to uplaod e-hentai files as it bypasses the tracker. Does it not?

Yes if you use the magnet link, but if you have DHT enabled it is not a problem.  (does not fix the issue)
There should be a feature implemented that would scan all the previously upload torrent files and add their trackers into the DB while removing the dead & duplicate trackers so the magnets will have the additional trackers.

**Comment by akuma06** [comment]
Should be fixed with #768
