### ISSUE TITLE
Edit and Mass Edit related

### ISSUE THREAD

**Issue by yiiTT** [NyaaPantsu/nyaa#720]
When you soft-delete a torrent you are unable to re-upload the same torrent. So when uploading it should check if the torrent was already deleted and allow you to re-upload.

On the other hand to un-delete a torrent that has been re-uploaded should be handled by a moderator who can hard-delete the torrent or similar.

The mass edit API/Tools should include the ability to change the status, owner, category and delete status to be used on the torrent list pages. This should also expand to the ability to mass delete torrent reports (using the current report delete endpoint by checking id args)

Add any missing features or requirements in a comment (mainly mods)

**Comment by yiiTT** [comment]
Pull Request: #719

**Comment by ShardM** [comment]
This will allow people to delete and re-upload the torrent, so it goes at the top of the list. Maybe have a timeout period. Maybe a few months after deletion before allowing re-upload.

**Comment by akuma06** [comment]
Should be done :). Comment part should be just an ajax query on PostComment so it's JavaScript side.

**Comment by yiiTT** [comment]
Looks like the edit button was removed, and /torrent/?id=## route does not display all the stuff to edit and save as a user.
