### ISSUE TITLE
Allow torrents to be hidden separate from status

### ISSUE THREAD

**Issue by yiiTT** [NyaaPantsu/nyaa#770]
When uploading a torrent you should have the ability to hide the torrent from the upload list (and the ability to un-hide). Instead of keeping the hidden status in "status" field it should be moved to it's own field so we can use the status still for remake, trusted, etc. 

There currently is no way for a user to mark or change their torrent to/from hidden.

**Comment by akuma06** [comment]
I will be working on it tonight if no one has done it.
It will be really simple :).

**Comment by akuma06** [comment]
Shoiuld be fixed in #789
