### ISSUE TITLE
Inadequate IPv6 support among default trackers

### ISSUE THREAD

**Issue by an-electric-sheep** [NyaaPantsu/nyaa#803]
The trackers added to magnets by default are mostly lacking IPv6 support.

No IPv6:

```
$ host -t AAAA tracker.doko.moe
tracker.doko.moe has no AAAA record
$ host -t AAAA tracker.coppersurfer.tk
tracker.coppersurfer.tk has no AAAA record
$ host -t AAAA zer0day.to
zer0day.to has no AAAA record
$ host -t AAAA tracker.leechers-paradise.org
tracker.leechers-paradise.org has no AAAA record
$ host -t AAAA tracker.opentrackr.org
tracker.opentrackr.org has no AAAA record
$ host -t AAAA tracker.internetwarriors.net
tracker.internetwarriors.net has no AAAA record
$ host -t AAAA mgtracker.org
mgtracker.org has no AAAA record
```

Has v6 DNS, but points to cloudflare bad gateway page:

```
$ host -t AAAA tracker.baka-sub.cf
tracker.baka-sub.cf has IPv6 address 2400:cb00:2048:1::6812:31d6
tracker.baka-sub.cf has IPv6 address 2400:cb00:2048:1::6812:30d6

$ lynx -dump http://tracker.baka-sub.cf/ 

   REFRESH(0 sec): [1]http://tracker.baka-sub.cf/

Error 522 Ray ID: 365d71ea469f2360 o 2017-05-28 01:30:17 UTC
```

only one that appears to work:

```
# host -t AAAA explodie.org
explodie.org has IPv6 address 2001:470:1:44a::209
# nmap -6 -p 1234,6969 -sU explodie.org

Starting Nmap 7.40 ( https://nmap.org ) at 2017-05-28 03:24 CEST
Nmap scan report for explodie.org (2001:470:1:44a::209)
Host is up (0.20s latency).
Other addresses for explodie.org (not scanned): 74.82.52.209
PORT     STATE         SERVICE
1234/udp closed        search-agent
6969/udp open|filtered acmsoda
```

**Comment by sfan5** [comment]
If you blindly add IPv6 support to all of those it will result in problems for seeders on a dual stack connection. (namely v4 peers not being able to connect to them)
Instead the list should contain alternative hosts for v4 or v6 of the same tracker.

**Comment by an-electric-sheep** [comment]
That is not correct. Clients can and should announce to both protocols when the tracker is dual-stack capable.

http://bittorrent.org/beps/bep_0015.html#ipv6

**Comment by sfan5** [comment]
I have just tested this with my local transmission instance, when announcing to `explodie.org:6969` no IPv6 traffic is observed despite it being available.
So it looks like separate announce URLs might actually be needed.

Where in the spec does it say that clients should announce over both v4 and v6 if possible?
Besides, the spec and actual implementation in clients can differ. I assume that trackers themselves would not [recommend](http://harry.lu/tracker/) multiple URLs if this was not necessary in practice.

**Comment by an-electric-sheep** [comment]
That paragraph mentions it:

> Clients that resolve hostnames to v4 and v6 and then announce to both should use the same key for both so that trackers that care about accurate statistics-keeping can match the two announces.

But yes, it does sound like optional behavior.
Anyway, the core issue is lack of v6 support among the default trackers, how exactly it is solved isn't important to me.

**Comment by an-electric-sheep** [comment]
This one could be added as v6-only tracker:

```
# nmap -6 -p 80,6969 IPv6.leechers-paradise.org -sU

Starting Nmap 7.40 ( https://nmap.org ) at 2017-05-28 20:36 CEST
Nmap scan report for IPv6.leechers-paradise.org (2001:9a8:0:e8::4)
Host is up (0.032s latency).
PORT     STATE         SERVICE
80/udp   closed        http
6969/udp open|filtered acmsoda

Nmap done: 1 IP address (1 host up) scanned in 1.51 seconds
```

**Comment by sfan5** [comment]
> > I have just tested this with my local transmission instance, when announcing to explodie.org:6969 no IPv6 traffic is observed despite it being available.

> Does transmission support ipv6 udp trackers?

A private tracker I'm on uses separate announce URLs for ipv6 and those work, so yes.

**Comment by an-electric-sheep** [comment]
Don't private trackers usually use http trackers?

**Comment by sfan5** [comment]
didn't see that you asked about udp

tried `udp://ipv6.tracker.harry.lu:80/announce`:
it tried to announce but the connection fails, however nothing seems to indicate that v6 udp is not supported

**Comment by sfan5** [comment]
I have added an ipv6 tracker in 3b6b81aa8d7c971d3612876c60685b17db0630fa (config is now [here](https://github.com/NyaaPantsu/nyaa/blob/dev/config/default_config.yml#L104))

@an-electric-sheep thoughts?

**Comment by an-electric-sheep** [comment]
LGTM
