### ISSUE TITLE
Site should put some "nyaa" in header or footer for better search engine ranking.

### ISSUE THREAD

**Issue by ijnokm9i** [NyaaPantsu/nyaa#817]
Googling  "nyaa", the Pantsu is in the second page (people do not click second page) and the page is FAQ, because it is the only page where the string nyaa can be found by Google crawler. Maybe the site icon should be change to plain text that explicit mentioned nyaa.

**Comment by tomleb** [comment]
We do have some SEO [https://github.com/NyaaPantsu/nyaa/blob/dev/templates/index.html#L7](https://github.com/NyaaPantsu/nyaa/blob/dev/templates/index.html#L7).

Not sure how much it affects this issue but google is removing a lot of links from us [https://www.google.com/transparencyreport/removals/copyright/searchdata/domains/?id=pantsu.cat](https://www.google.com/transparencyreport/removals/copyright/searchdata/domains/?id=pantsu.cat)

**Comment by ijnokm9i** [comment]
A minimal change that might help is
* Add a space in the footer, from "Powered by NyaaPantsu" to "Powered by Nyaa Pantsu" 
* Add a space in the alt text of the logo.
