### ISSUE TITLE
Elasticsearch fails the k-on test

### ISSUE THREAD

**Issue by tomleb** [NyaaPantsu/nyaa#818]

**Comment by simonard** [comment]
Search for "けいおん" instead

**Comment by lc-guy** [comment]
Shit show anyway, pls nofix

**Comment by dumbwanker** [comment]
You know this is an issue for any show with a - in the title?

Suggesting not to fix it because you're not a fan of one show that contains a dash is quite stupid if you ask me.

**Comment by tomleb** [comment]
This has been fixed already, see [dev](https://dev.pantsu.cat/search?c=_&max=50&order=false&q=k-on)

**Comment by lc-guy** [comment]
I think there's this concept called "a joke"...
