### ISSUE TITLE
Make some sort of upload management that delete torrents if the same file already exit

### ISSUE THREAD

**Issue by egozi44** [NyaaPantsu/nyaa#822]
So I usually don't mind by seeing the same torrent and file more than once... but here it seem like some people uploading the same episode (mostly of horriblesubs) over and over again resulting in getting the same ep in 2-3+ different torrents with the same name, I don't know if it out of good will or just people who want to spam the site but that thing really annoy, is there any idea you could use to stop users or unregister users from uploading the same file billon of times?

**Comment by xtj-9182** [comment]
I agree. Take a look at this:
![nyaa duplicates](https://cloud.githubusercontent.com/assets/9414008/26588462/b4307982-4555-11e7-8a91-5275d86108a6.png)
how many berserk 21 480p do we need xD

**Comment by akuma06** [comment]
You can't upload the same torrents and there is already a tool that deletes automatically a torrent with the same hash when a user ownes a torrent that he has soft deleted.

Seems like it's the scrapper which create duplicates.

**Comment by sfan5** [comment]
Might be a bug with the API only

**Comment by akuma06** [comment]
@sfan5 I just looked and there is a check on the hash when you upload with the api. It is the scrapper that makes this

**Comment by akuma06** [comment]
@ewhal is it still a thing?

**Comment by xtj-9182** [comment]
not sure if the scraper bug is fixed but the duplicates are definitely still there and need to be removed.
