### ISSUE TITLE
Changing Theme Messes with Mascot Audio

### ISSUE THREAD

**Issue by lehitoskin** [NyaaPantsu/nyaa#824]
Changing the theme to get a new mascot will mess with the audio if you reload the page or search for something.

Steps to reproduce:
1. Change theme from "Default" to "Tomorrow"
2. Search for something
3. Click the mascot

Expected result: The audio snippet is consistent with the visible mascot for the theme
Actual result: The audio snippet that is played is from the "Default" theme

**Comment by akuma06** [comment]
Can't reproduce your bug, seems like it has been fixed in dev.pantsu.cat
