### ISSUE TITLE
expand categories drop-down

### ISSUE THREAD

**Issue by solinium** [NyaaPantsu/nyaa#835]
This is a minor issue, but the categories drop-down at the top is not wide enough, and on its default option 'All Categories' it is cut off.
![screenshot](https://i.imgur.com/OuGZyCD.png)

**Comment by kipukun** [comment]
This isn't an issue on latest dev HEAD. It seems to be more of an issue with the font you're using.

**Comment by solinium** [comment]
@kipukun You're probably right, my bad
