### ISSUE TITLE
Search Inferior to Old Design

### ISSUE THREAD

**Issue by Taien** [NyaaPantsu/nyaa#847]
This is a matter of opinion and you can close it if you wish, but I think the new search setup is vastly inferior to the old one.  Previously I could set category to anime, show results only from the last 7 days, and order by downloads, which pretty much kept me up to date on the newest releases.  Now, you can only search by one or the other (date or downloads), and either way, you're not getting the results you want.  Please find a way to implement the old search system (perhaps with a new web design setup but preserving the original functionality).  

The way it's set up now, I have to wade through all the crap posts to find the good ones, no matter which method I use.

**Comment by tomleb** [comment]
What do you mean by old design ? I don't remember being able to do that. (Yes, search needs improvement)

**Comment by Taien** [comment]
So like on nyaa.se you could go up to the search bar, type nothing and
select anime, and then hit search.  And above the result set would be some
extra fields like "Show only results within ___ to ___ days".  So then I
would put a 7 in the second field there and click Refine or whatever the
button said.  So my result set would then be all anime within the last 7
days.  Then I clicked the column heading for downloads, and it would sort
that result set (last 7 days of anime) by amount of downloads.  That's the
functionality which currently seems to be missing on the live site, unless
I'm just not seeing it.

**Comment by akuma06** [comment]
I wanted also to add the search by date functionality, but I would need @tomleb to add a date field in ElasticSearch for torrents

**Comment by tomleb** [comment]
There already is a date field in ES.

**Comment by akuma06** [comment]
O-Oh there is? The same as the torrents ? =D.

**Comment by akuma06** [comment]
The field have been implemented, we just miss where we should put them. Any idea @kipukun ?

**Comment by kipukun** [comment]
![capture](https://cloud.githubusercontent.com/assets/6733106/26735285/3c9f28c8-478f-11e7-83c4-753f3a4fb20f.PNG)
This is what @Taien is referring to. It only shows when making a search. I'd have to think on where to position it in our current setup.

**Comment by kipukun** [comment]
This is completed in the latest dev, yay!
