### ISSUE TITLE
visiting dev.pantsu.cat redirects to a.doko.moe

### ISSUE THREAD

**Issue by steindornatorinn** [NyaaPantsu/nyaa#850]
When I try to visit dev.pantsu.cat I get redirected to this page.

<img width="960" alt="dev" src="https://cloud.githubusercontent.com/assets/12187513/26587426/e86bc1e8-4541-11e7-8a1f-75eb3d54ffcb.png">

This only happens on windows, but it happens across all browsers.

**Comment by cfrank** [comment]
Happens on Linux as well.

**Comment by mitki** [comment]
The https version is working fine, that's weird. Probably it's a webserver config issue.

https://dev.pantsu.cat/ -> Working fine.
http://dev.pantsu.cat/ -> Trigger the bug.

**Comment by mitki** [comment]
http://doko.moe is affected as well, so it's unrelated to NyaaPantsu.

**Comment by alucard0134** [comment]
fix'd

**Comment by steindornatorinn** [comment]
It lands me on a default ngnix page now?

**Comment by akuma06** [comment]
Still redirecting you?

**Comment by mitki** [comment]
Yeah `curl -I dev.pantsu.cat` does not redirect to the https version, instead, it shows the fedora's default nginx page.

**Comment by steindornatorinn** [comment]
Ditto
