### ISSUE TITLE
Mascot settings not saving on page reload

### ISSUE THREAD

**Issue by cfrank** [NyaaPantsu/nyaa#851]
When pressing "Mascot" next to the theme switcher the mascot gets toggled, but the settings are not saved, so the next time a page is loaded the mascot is back.

**Steps to reproduce**

- Click the mascot toggle button.
- Reload the page

**What should happen**

Mascot should be toggled, and the setting should be saved

**What is happening**

No local storage settings are being saved

_I can take this on if nobody has any objection,_

**Comment by cfrank** [comment]
This might be fixed by #827 

Has that not been applied to the live site?

**Comment by mitki** [comment]
Yeah it's fixed, but it's not applied to the production yet.

**Comment by cfrank** [comment]
Closing
