### ISSUE TITLE
Mascot Sound Does Not Match

### ISSUE THREAD

**Issue by FelixGP** [NyaaPantsu/nyaa#856]
When the site is opened, if your previously used theme is loaded from cookies (I assume it's cookies) the mascot sound does not match up with the mascot. Eg.:
>Open site and choose tomorrow theme
>Close site
>Reopen site; theme is automatically set to Tomorrow
>Clicking Megumin produces the sound "Nyanpasu"
>Need to change theme then change back for the sound to change to "Explosion"
Seems like a pretty easy fix, but my knowledge of HTML/CSS and coding in general is pretty bad.

**Comment by steindornatorinn** [comment]
Already fixed and just waiting to be pushed to production.
