### ISSUE TITLE
Report system not working - no captcha

### ISSUE THREAD

**Issue by toynbeeidea** [NyaaPantsu/nyaa#864]
I know you completely ignore reports, but so long as you're still pretending:  If I attempt to report a torrent, I can't, because no captcha appears, and I get a "bad captcha" response.

**Comment by steindornatorinn** [comment]
Can confirm, also happens on the latest build.

Did this work at some point or was it never implemented properly?

**Comment by akuma06** [comment]
I think since new kipukun theme it doesn't work anymore~

**Comment by steindornatorinn** [comment]
Allright so someone has intentionally disabled reports from users, but left the button behind.
Is the plan not to have the button there, or to fix something and re-enable it?

**Comment by akuma06** [comment]
works now~

**Comment by akuma06** [comment]
Reports works only when logged as trusted users/admin :/

**Comment by steindornatorinn** [comment]
Yeah, the captcha doesn't work in the context of the JS-created-window.

People seem to really like the popup report window, but I don't feel like repacing the captcha system in order to keep it. Plus it's a ugly hack tbqhwy.

**Comment by ewhal** [comment]
Bringing back modal report system would be far more sane.
No need for the js popup window.

**Comment by kipukun** [comment]
I was trying to replicate 4chan's system since I liked it, but since we already have modal code for mod tools, may as well apply it to this case as well.

**Comment by akuma06** [comment]
Seems to be fixed by #935
