### ISSUE TITLE
Issue, reports and suggestions~

### ISSUE THREAD

**Issue by egozi44** [NyaaPantsu/nyaa#867]
So first to the issue:

1. I got my home language being displayed in both sites in the date section rather than English (and the site is set to English) or numbers to the point it unreadable thanks to the fact the design not was build for such long words, please change it back to numbers only >.>

List of things I and others reported so far and still around (if you working on it, it alright, just wanted to point it out in case you don't aware it still happens):

1. site tend to be overlord/fall
2. User will be log out when you close the browser and there's no remember me button.
3. Site look pale without proper color in the background than  black and white, the eyes can just get lost in that simple colors and many categories can get mixed because they all white, especially if you use big resolution.
4. Commits still don't display avatar and don't have proper color to them (I recall I suggest the color thingy somewhere and someone here said he working on it but I didn't saw any chance since then... unless it was cancelled.)
5. Mascot sound gave me heart attack (You can ignore this one ^^)

Suggestions:

1. Any chance that you can add the category tag to the torrent page as well? I think it was like that in old nyaa and even if wasn't there's one rule my eyes keep follow: "One picture worth thousand of words"

When everything is in pale words and in big resolution it look so god dam small to the point the eye can miss it or mistake it to something else easily unless if there's proper location and color to it.

Adding the tags will give people easy time noticing what kind if category they currently watching.

![g](https://cloud.githubusercontent.com/assets/14190834/26645557/127bebca-4641-11e7-97ed-cd2d7a3145b1.PNG)
![6](https://cloud.githubusercontent.com/assets/14190834/26645563/163673de-4641-11e7-8780-f68b9c350ff3.png)

2. adding other default mascots to Sukebei, (and also different background from the main site as I mentioned before) it can be for example Risa gergory from DxD and red background or whatever on your mind, we can change mascots now so non non can still appaer there, but if the macot and background will be different from the other site it will be easier to not mistake between the two.

**Comment by MaeJhem** [comment]
1. A new issue was created about scraping. It makes the site overlaod/slow.
3. The site looks better than before.

Hey, I want to talk to you with something, do you have any email or discord account? :+1:

**Comment by steindornatorinn** [comment]
Thanks for taking the time to compile this @egozi44 , it really helps a lot.

Regarding 3. are there any objections to making /g/ the default theme? IMO the current default looks very bootstrap-default-y. @kipukun do you have any thoughts on this?

**Comment by mitki** [comment]
![img](https://0x0.st/6S_.png)
1. You have a point, dates should not be translated, since it's capped in many languages.

The design is way better than before imo, but I'm only using the dark one.

**Comment by egozi44** [comment]
> A new issue was created about scraping. It makes the site overlaod/slow.
Scrapping is that software that access and extract data and etc correct? how can it be fixed then?

>     The site looks better than before.
Agree but we can probably make it look even better, I never noticed it till old nyaa was dead, but it's simple design was what made it comfortable to use.

> Hey, I want to talk to you with something, do you have any email or discord account? 👍
I have discord but I rarely uses it, I have mail and skype if you want to chat but if it related to web developing I afraid my knowledge is limited. I do have some skills in PS though.


> Thanks for taking the time to compile this @egozi44 , it really helps a lot.
> 
> Regarding 3. are there any objections to making /g/ the default theme? IMO the current default looks very bootstrap-default-y. @kipukun do you have any thoughts on this?
Np

Well considering that I don't quite sure what "bootstrap" mean in that regard (I assume it something bad though) I don't sure if I can answer that, but iirc (since the site is currently down again and I can't check it) they both don't have colorful background, You can take the old nyaa's green them to make us feel at home ;) but if you want other color, go ahead, as long as it not white or black I will be happy (I hope...)

**Comment by MaeJhem** [comment]
@egozi44 Yes, they scarpe the current/updated seeders/leechers/completed. Well it will make sense if they added the scapers on every pages.

"bootstrap", it is a built in css framework. (for lazy person). 

Give me you skype then :+1:

**Comment by egozi44** [comment]
Actually for various reasons, mind to give me yours instead? xD

**Comment by kipukun** [comment]
Different themes should be opt-in, not opt-out. Similar to 4chanX, a default theme isn't applied for you. You can choose to have a theme though.

**Comment by egozi44** [comment]
Most of the issues I pinned here still present unfortunately :/

I also noticed that the commits are displayed more than three times

![yufgufg](https://user-images.githubusercontent.com/14190834/26838373-8f038378-4ae8-11e7-8a1a-ef73de963a38.PNG)

**Comment by steindornatorinn** [comment]
Fixing bugs takes time, and deployment takes time too. Expect to see the first fixes in ~2 weeks. If you want to speed things up, contributions are always welcome :).

**Comment by egozi44** [comment]
Yea I know how it hard to fix things up (been in some mod's projects before and one of them took few sweet years of my life xD), If I could be of any help I would've join but unfortunately my coding skills are poor :"|
