### ISSUE TITLE
Add some filter in RSS

### ISSUE THREAD

**Issue by vi000246** [NyaaPantsu/nyaa#878]
Origin Nyaa have date and size filter.
use case:
    date filter : search between 1day and 7days old record
        https://sukebei.nyaa.si/?page=rss&minage=1&maxage=7

    size filter : search between 100MB and 500 MB record
        https://sukebei.nyaa.si/?page=rss&minsize=100&maxsize=500

And I found RSS cannot jump to another page.
Hope can add querystring to search page in RSS
ex.    
     jump to third page.
        ?page=rss&p=3

And I hope can put torrent link and download count in RSS item
thanks your awesome website.

**Comment by ElegantMonkey** [comment]
There is pagination support for RSS feeds:
`https://nyaa.pantsu.cat/feed/3?querystring`

**Comment by akuma06** [comment]
You can search page in RSS with /feed/page_number/

This commit #881 has added a date filter: ?fromDate=2017-06-01&toDate=2017-06-02 <= this will get the torrents from yesterday and today
And also a maxage filter: ?maxage=7 <= this gets the torrents from the last seven days

**Comment by vi000246** [comment]
It's clear to me now.
Thank you.
