### ISSUE TITLE
Uploading torrents lack many options

### ISSUE THREAD

**Issue by egozi44** [NyaaPantsu/nyaa#889]
So I tried uploading my first torrent here and noticed that I have Way less features compared to old nyaa and Nyaa SI

1. You don't have option to post as anonymous
2. Tracker list not present in the upload page (they should be so people will know what to add without to look at the faq, and btw the faq github link is broken)
3. You can't delete torrent you uploaded
4. You can't edit your own torrents
5. You should add tags info and preview button

Personally I prefer to upload as anonymous but now I can't edit my torrents, delete them, or have anonymous button...

Please add these features

**Comment by akuma06** [comment]
1. There is, it is not on last build
2. You don't have to think about it, we add trackers on the torrent automatically and we keep the ones that you've added
3. You can, not on last build
4. You can, not on last build

**Comment by egozi44** [comment]
So when the last build will be up ? :0

**Comment by akuma06** [comment]
I asked and it should be up today =)

**Comment by egozi44** [comment]
I see, thanks :P

Btw will we be able to edit torrents we uploaded pre the last build?

**Comment by egozi44** [comment]
Well, new build was up but aside the new default skin I don't see any new torrent options :/
also it was suggested but will we see uploader's subscribe option in the future?

**Comment by akuma06** [comment]
What? When you're logged there is the mark as anon checkbox.
And if you're logged, you can "follow" another user which leaves you a notification every new upload (if enabled in your settings)

**Comment by egozi44** [comment]
let me retest it then, I tried look in the upload page few hours ago and also to change my old torrent go ano but didn't found box or edit button.

**Comment by egozi44** [comment]
yup just check it, not edit or ano button (unless it the hidden box which should be change to anonymous as it misslead)

The phone version of the site also don't have fap/fun button.

I also noticed that strangely enough the site look better and less mess up on phone browsers  After you turn on desktop view in the browser options compared to the normal pc view (which have way bigger resolution and made the torrent's list to look small and stick in the middle of the page, and the profile page to look mess up (one button upon each other)

**Comment by egozi44** [comment]
oh just one more thing I should mention, There's a different between log in as anonymous and Upload as anonymous, though I can't even log in as annynomus  (there's no box) Old nyaa never worked that way, you could uploaded as anonymous without create a user OR you could create a user, upload torrent, and check a box in the upload page which will display it as annynomus to others But not to you (you will see "anonymous  (Your user name)" in the torrent page if you log in.

What the difference? is that you could still see your own torrents in your torrent page even if you uploaded them when checking the annynomus box, which let you also edit and delete them Any time.

**Comment by akuma06** [comment]
But you have it! Mark as hidden. It's to hide who uploaded the torrent from others (so as anon)

**Comment by akuma06** [comment]
However delete and edit buttons seem to not work where they work on my build. Dunno why, might be an issue with deployment

**Comment by egozi44** [comment]
hide button is misleading name, it make you think your torrent will be hidden from others and only viewable to you as the uploader.

So far all of these new buttons aren't avaliable unfortunately  :0

**Comment by akuma06** [comment]
Edit and delete were added on last commit 10 hours ago for users. Still have to wait the new build

**Comment by egozi44** [comment]
Still can't edit my torrent at all though,
I finally found the follow button but I think it will be easier to spot if it will be in the same torrent page like old nyaa

In old nyaa it was here:


![321](https://user-images.githubusercontent.com/14190834/26838488-edfea98e-4ae8-11e7-9262-8ecf71ee27eb.PNG)


BTW is there any chance to review old seeders somehow? I keep seeing zero seeders or unknown number of seeders in any torrent before april (before nyaa died) and on other sites I see them they show they have many seeders, I assume that because they still show preview of the old nyaa tracker with some people foolishly still seed to,
However it not change the fact that 90% of the old torrents are undownloadable, is there some way to forcfully change the old nyaa tracker to yours so we won't lose the old seeders?

We can't count ons sites like BBT now to get old shows and that will literally mean most shows of the erailer 2000- are dead (unless someone will start reupload all old shows from BBT and such one by one...)

**Comment by egozi44** [comment]
Btw here the torrent upload page in Nyaa.si
There you can hide it from the list, and make it as anonymous together
![2](https://user-images.githubusercontent.com/14190834/26858268-dcfa8aa4-4b38-11e7-9908-fe6d782ac028.PNG)


That how most sites do it afaik
