### ISSUE TITLE
Ugly page when torrent not found.

### ISSUE THREAD

**Issue by JesusAMR** [NyaaPantsu/nyaa#891]
When there isn't a torrent available for download an ugly page appears.
![image](https://cloud.githubusercontent.com/assets/16111357/26749277/1066dc0e-47cd-11e7-90df-d9d9f37a6deb.png)

**Comment by mitki** [comment]
It's unrelated to NyaaPantsu actually, as you can see from the url in the address bar.
Maybe we should contact ilikecats, the gibberish on line 2 were supposed to be kanji, the website is missing a meta charset tag.

**Comment by sfan5** [comment]
\>2017
\>browsers still don't assume utf-8 by default
![bildschirmfoto_2017-06-03_12-16-13](https://cloud.githubusercontent.com/assets/1042418/26752702/95b37208-4856-11e7-828b-60f6445c6643.png)

added a meta charset tag, should be fixed now
