### ISSUE TITLE
New 404 page design ?

### ISSUE THREAD

**Issue by tomleb** [NyaaPantsu/nyaa#893]

**Comment by Kiloutre** [comment]
![404](https://cloud.githubusercontent.com/assets/11745692/26749544/aff02d8a-480d-11e7-88ff-f9dd437d4fad.png)
current one broke after some recent changes
also two mascots is redundant

**Comment by akuma06** [comment]
@Kipukun has modified it and I also fixed the redondant mascot in #952

**Comment by kipukun** [comment]
I still have to make it look better though. Will be working on.
