### ISSUE TITLE
Not setting uploaderID with TorrentJSON when Uploader == nil

### ISSUE THREAD

**Issue by tomleb** [NyaaPantsu/nyaa#899]
![https://my.mixtape.moe/kiqzbm.png](https://my.mixtape.moe/kiqzbm.png)
From the picture, when uploading, we set only the UploaderID to the Torrent struct. Afterward, for ES indexing, we do torrent.ToJSON(), but since the Uploader hasn't been set, the UploaderID is 0. This results in wrong UploaderID in ES index.

**Comment by AnthonyFoley** [comment]
Maybe related: Can you also check torrent ID 924740 "../../delete_me.torrent🙂5" on dev, I created it under the username `anime_is_bad` but it doesn't even show in my profile page, I don't remember if I checked "hidden". Don't know what and how I did it.

**Comment by akuma06** [comment]
Fixed by #930
