### ISSUE TITLE
 driver: bad connection

### ISSUE THREAD

**Issue by ewhal** [NyaaPantsu/nyaa#926]
Postgresql issue
Occasionally users will get "driver bad connection" error message when loading pages.
Found https://github.com/lib/pq/issues/349
I had a return statement inside for rows.Next() which left an open connection each time the function executed until the db connection was lost.
We're possibly leaving db connections open.

**Comment by akuma06** [comment]
defer rows.Close() <= seems like we do it before making a for loop on rows.Next

**Comment by Jagalite** [comment]
> Occasionally users will get "driver bad connection" error message when loading pages.

Which pages specifically?

> I had a return statement inside for rows.Next() which left an open connection..

Can you give an example of the file/lines you are referring too?
