### ISSUE TITLE
    Why do the homepage and page 1 have different content? Shouldn't they be the same?

### ISSUE THREAD

**Issue by ewhal** [NyaaPantsu/nyaa#928]
Why do the homepage and page 1 have different content? Shouldn't they be the same?

    https://nyaa.pantsu.cat/
    https://nyaa.pantsu.cat/search/1?

    Also seems like page 1 has hentai.

**Comment by akuma06** [comment]
Is it no fixed, I don't see any difference now?

**Comment by tomleb** [comment]
It was because we had two different routes. / was using postgresql (ie: not considered a search) and /search uses es.
If it wasn't done yet we're probably going to make / == /search/1 instead and stop using the other route.
@ewhal Was it done yet ?

**Comment by akuma06** [comment]
It was done already :)
