### ISSUE TITLE
torrents sometimes show up completely empty

### ISSUE THREAD

**Issue by sfan5** [NyaaPantsu/nyaa#940]
![bildschirmfoto_2017-06-06_01-55-09](https://cloud.githubusercontent.com/assets/1042418/26808160/53a2ceca-4a5b-11e7-819b-4f097399daa1.png)

**Comment by akuma06** [comment]
They are not empty, they use some unicode like &zwnj;&#65279;

**Comment by akuma06** [comment]
‌﻿

**Comment by sfan5** [comment]
Yes they are, notice the absence of an uploader or hash.

**Comment by akuma06** [comment]
But then how can you have empty torrent? I can't reproduce it on dev

**Comment by sfan5** [comment]
the torrent isn't actually empty, it just shows like this sometimes
if you refresh it shows up okay
