### ISSUE TITLE
Remaining style issues

### ISSUE THREAD

**Issue by sfan5** [NyaaPantsu/nyaa#949]
@kipukun 

* torrent list is too narrow IMO, the title column should be longer
* search bar overlaps profile thingy in modpanel
* mod bar buttons need styling
* "save changes" button is in line below mod bar
* modpanel table contents are not centered vertically
* button text in modpanel cut off (torrents, users and comments table)
![](https://my.mixtape.moe/dhgzqp.png)
* view pg: download & magnet button are not prominent enough (in comparison to other buttons)
* <b>view page does not show old uploader name (if present in db)</b>

**Comment by kipukun** [comment]
サンキュー
