### ISSUE TITLE
cookie for theme/mascot doesn't carry over between domains

### ISSUE THREAD

**Issue by solinium** [NyaaPantsu/nyaa#950]
![dark](https://i.imgur.com/46qv9ul.png)
![light](https://i.imgur.com/v2LjzsF.png)
if I have dark theme w/ mascot selected on nyaa.pantsu.cat it doesn't carry over to pantsu.cat
possibly just have pantsu.cat redirect to nyaa.pantsu.cat?

**Comment by akuma06** [comment]
should be fixed by #951
