### ISSUE TITLE
Cloudflare Email Protection

### ISSUE THREAD

**Issue by MMP0** [NyaaPantsu/nyaa#965]
Double-byte character languages

![Thai](https://user-images.githubusercontent.com/28616020/26884706-5e58b830-4bdb-11e7-82d2-68923f3eec2a.PNG)

![Japanese](https://user-images.githubusercontent.com/28616020/26884711-60e8be2e-4bdb-11e7-87ed-a66e0a353f4f.PNG)

**Comment by akuma06** [comment]
Should be fixed by #c9c170

**Comment by akuma06** [comment]
#
