### ISSUE TITLE
(dev) Settings menu no longer works

### ISSUE THREAD

**Issue by steindornatorinn** [NyaaPantsu/nyaa#966]
I wanted to check if things worked in spanish now, but I can't :(.

**Comment by akuma06** [comment]
On dev.pantsu.cat ?

**Comment by steindornatorinn** [comment]
No the latest build, running locally.

**Comment by akuma06** [comment]
Seems to work fine for me: ![](http://puu.sh/wdJ6l/dad4529099.jpg)

**Comment by steindornatorinn** [comment]
Git seems to have been messing with me, after hard resetting it works fine.

**Comment by steindornatorinn** [comment]
The issue is back for me, I'm going to leave this open in case someone else is experiencing this. Broke this time while I was messing with .css files which makes no sense whatsoever.

**Comment by steindornatorinn** [comment]
After some more testing, this seems to happen at completely random after building+starting up the server. I'm going to leave this issue open in case someone else experiences this, but I'm starting to strongly suspect this has something to do with my setup.
