### ISSUE TITLE
Add commit number count next to each torrent in the torrent's list

### ISSUE THREAD

**Issue by egozi44** [NyaaPantsu/nyaa#969]
I recommend that you add commits number count next to each torrent in the torrent's list like old nyaa did (Nyaa.si also added it) 

It help people know is there's commits before entering to the torrent page.

**Comment by akuma06** [comment]
They are on nyaa.pantsu.cat

**Comment by egozi44** [comment]
how come I can't see them? :0

**Comment by akuma06** [comment]
Refresh your cache: ![](https://puu.sh/wdL7H/9bfef4f031.png)
It's the "1"

**Comment by egozi44** [comment]
site not accessible at all atm, all I got is bounch of html codes for the main page

**Comment by egozi44** [comment]
Now I know why I can't see it, it because the date in different lanuage thingy I reported week ago

![hgfhf](https://user-images.githubusercontent.com/14190834/26903838-d0bc0042-4be7-11e7-8ca8-971dd5079a88.PNG)


You should change it to numbers to avoid such issues
