### ISSUE TITLE
order by date is wrong when searching

### ISSUE THREAD

**Issue by xtj-9182** [NyaaPantsu/nyaa#972]
when I search for something, for example "horrible".

this is what I see:
![nyaa bug](https://user-images.githubusercontent.com/9414008/26973889-f62192fc-4d18-11e7-84d0-b08a7a2c958a.png)

the date indicator shows that it *should* show newest first but it doesn't do that.
Either make the indicator blank or make it actually sort correctly. Do note that clicking on the indicator will make it actually sort correctly.

**Comment by akuma06** [comment]
Thanks for the bug reporting and searching where it comes from. I've seen this behaviour but didn't have time to look into it.
It seems to come from the default order when searching with ES. @tomleb should be able to fix it quickly if it still does it on last commit (can't test now)

**Comment by tomleb** [comment]
We're going to default sorting by date instead of by id. Should fix it. Where is the default sort (from config.yml) used ? Just want to see if ES search uses that.

**Comment by akuma06** [comment]
The config comes from here: https://github.com/NyaaPantsu/nyaa/blob/dev/config/default_config.yml#L123
However you're not using it in default sort type structure used in common/search.go
