### ISSUE TITLE
Use torrent files links instead of magnet links in RSS feeds

### ISSUE THREAD

**Issue by TyrantRC** [NyaaPantsu/nyaa#977]
This is not really a bug but an annoyance. Nearly everyone in the tracker scene use RSS feeds with "torrent file links" because several clients have problems executing magnet links when using automatic donwload features.

Here is how Patsu does the feeds:
![1](https://user-images.githubusercontent.com/16332298/27005352-2c16ff5a-4deb-11e7-8a15-71e1aed7abe6.jpg)

Here is how several trackers for anime do their feeds

Animebytes:
![2](https://user-images.githubusercontent.com/16332298/27005362-3e0e5bc2-4deb-11e7-9417-0bebeadd1372.jpg)

Anidex:
![3](https://user-images.githubusercontent.com/16332298/27005364-46013e08-4deb-11e7-982a-c4efe2fb3e89.jpg)

Shanaproject:
![4](https://user-images.githubusercontent.com/16332298/27005373-7253a2e8-4deb-11e7-89c6-1e869ee1bab5.jpg)

And Nyaazi:
![5](https://user-images.githubusercontent.com/16332298/27005375-7e834186-4deb-11e7-8fd4-d08f41c2f5e6.jpg)

----
And this is what happen in my client when it tries to process the magnet link:
![6](https://user-images.githubusercontent.com/16332298/27005532-0ce9035a-4dee-11e7-8fb6-15f4f9489545.jpg)

----
In my case I could just upgrade my client version of qbittorrent to the 3.2 version since the issue was fixed there, but I don't think is worth for me to upgrade just to be able to use one tracker when I can just use another one. As I'm almost sure that I'm not the only one in this predicament I'm doing this issue for them too.

**Comment by cfrank** [comment]
I could look at this on Monday is nobody else is interested in it. If nobody objects or puts in a PR I'll take it.

**Comment by ewhal** [comment]
We need to generate a lot of torrent files.
That's why it hasn't been done
