### ISSUE TITLE
Duplicated comments

### ISSUE THREAD

**Issue by niririke** [NyaaPantsu/nyaa#986]
[Here](https://nyaa.pantsu.cat/view/810999) is an example.
![comments0](https://user-images.githubusercontent.com/25935399/27056914-a756b01e-4fd2-11e7-9ebe-c626a5dceca1.png)

**Comment by niririke** [comment]
@egozi44 actually already mentioned it [here](https://github.com/NyaaPantsu/nyaa/issues/867#issuecomment-306529296), but let's have it as a separate issue I guess.

**Comment by egozi44** [comment]
As long as it will be brought to the dev team attention everything work I guess (aside using love notes)

**Comment by niririke** [comment]
I think it's not only about devs' awareness. Some dude may come here and conclude that devs don't know about the issue. That's what happened with me anyway.

So, devs say the issue will be solved with a next server maintenance. Let's wait for that.

**Comment by akuma06** [comment]
@ewhal 
```
 DELETE FROM comments_old USING comments_old c2 WHERE comments_old.content=c2.content AND comments_old.date < c2.date
```

**Comment by niririke** [comment]
The particular example has been fixed. I hope that it's actually fixed everywhere.
