### ISSUE TITLE
RSS links giving invalid links

### ISSUE THREAD

**Issue by afannyaa** [NyaaPantsu/nyaa#998]
When I logged in to check by downloading torrent file or magnet (in case my rss was playing up) and was given 404's when clicking on the magnet or torrent file links.

One such rss is:
https://nyaa.pantsu.cat/feed?c=_&s=0&max=50&userID=0&q=horrible+akashic+1080

when doing the same search on the website:
https://nyaa.pantsu.cat/search?c=_&s=0&max=50&userID=0&q=horrible+akashic+1080

the episodes 9, 10 and 11 got to 404.

**Comment by akuma06** [comment]
I don't see any problem with those links though

**Comment by afannyaa** [comment]
it's not the links, it's what they point to.
For eaxmple, in that search link, when you try to interact with the results (magnet and torrent dl for specific torrents) from the search - those results will 404

**Comment by akuma06** [comment]
Ok the bug is not from the rss links specifically. They come from the shi... scrapper which add torrents hashed without stripping whitespace :p.
